// AHA Chat Persistence V1 – local, review-gated chat memory for Data Intake.
(function (global) {
  "use strict";
  const VERSION = "v1";
  const STORAGE_KEY = "aha_chat_sessions_v1";
  const CURRENT_SESSION_KEY = "aha_chat_current_session_v1";
  const MAX_SESSIONS = 25;
  const MAX_MESSAGES_PER_SESSION = 400;
  function storage(){ try { return global.localStorage || null; } catch { return null; } }
  function arr(v){ return Array.isArray(v) ? v : []; }
  function obj(v){ return v && typeof v === "object" && !Array.isArray(v) ? v : {}; }
  function text(v){ return String(v ?? "").replace(/\s+/g," ").trim(); }
  function now(options={}){ return new Date(options.now || Date.now()).toISOString(); }
  function id(prefix="chat"){ return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`; }
  function hash(value){ const s=text(value).toLowerCase(); let h=5381; for(let i=0;i<s.length;i++) h=((h<<5)+h+s.charCodeAt(i))>>>0; return `chat_${h.toString(36)}_${s.length}`; }
  function uniq(v){ const seen=new Set(); return arr(v).concat(typeof v === "string" ? v.split(",") : []).map(x=>text(x?.label||x?.name||x)).filter(Boolean).filter(x=>{const k=x.toLowerCase(); if(seen.has(k)) return false; seen.add(k); return true;}); }
  function parse(raw, fb){ try { const v=JSON.parse(raw); return v == null ? fb : v; } catch { return fb; } }
  function compact(value){ const o=obj(value); return { id:text(o.id)||id("answer_ref"), status:o.status||null, score:Number(o.score)||Number(o?.status?.score)||0, summary:text(o.summary||o.title||o.status?.intent).slice(0,240), generatedAt:text(o.generatedAt)||now() }; }
  function normalizeMessage(input, sessionId){ const o=obj(input); const role=["user","assistant","system"].includes(text(o.role)) ? text(o.role) : (text(o.role)==="aha"?"assistant":"user"); const createdAt=text(o.createdAt)||now(); return { id:text(o.id)||hash(`${sessionId}:${role}:${createdAt}:${o.text||o.message||""}`), type:"chat_message", role, text:text(o.text||o.message||o.content), createdAt, sessionId, source:text(o.source)||"aha_chat", intent:text(o.intent), project:text(o.project), tags:uniq(o.tags), concepts:uniq(o.concepts), answerPackageId:text(o.answerPackageId), answerEvaluationId:text(o.answerEvaluationId), retrievalSummary:text(o.retrievalSummary), meta:{...obj(o.meta)} }; }
  function normalizeSession(input){ const o=obj(input); const createdAt=text(o.createdAt)||now(); const sid=text(o.id)||id("chat_session"); const messages=arr(o.messages).map(m=>normalizeMessage(m,sid)).filter(m=>m.text).slice(-MAX_MESSAGES_PER_SESSION); return { id:sid, type:"aha_chat_session", title:text(o.title)||messages.find(m=>m.role==="user")?.text?.slice(0,80)||"AHA Chat session", createdAt, updatedAt:text(o.updatedAt)||messages.at(-1)?.createdAt||createdAt, source:text(o.source)||"aha_chat", messages, meta:{...obj(o.meta), active:o.meta?.active !== false} }; }
  function loadSessions(){ const list=arr(parse(storage()?.getItem(STORAGE_KEY)||"[]",[])).map(normalizeSession).filter(s=>s.meta?.active!==false); return list.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))); }
  function saveSessions(sessions){ const normalized=arr(sessions).map(normalizeSession).slice(0,MAX_SESSIONS); try { storage()?.setItem(STORAGE_KEY, JSON.stringify(normalized)); } catch {} return normalized; }
  function getOrCreateCurrentSession(options={}){ const sessions=loadSessions(); const currentId=text(options.sessionId)||text(storage()?.getItem(CURRENT_SESSION_KEY)); let session=sessions.find(s=>s.id===currentId) || sessions[0]; if(!session){ session=normalizeSession({ id:id("chat_session"), title:options.title, createdAt:now(options), updatedAt:now(options), meta:{active:true} }); sessions.unshift(session); saveSessions(sessions); } try { storage()?.setItem(CURRENT_SESSION_KEY, session.id); } catch {} return session; }
  function replaceSession(session){ const sessions=loadSessions().filter(s=>s.id!==session.id); return saveSessions([normalizeSession(session), ...sessions])[0]; }
  function addMessage(input){ const session=getOrCreateCurrentSession({ sessionId:input?.sessionId }); const message=normalizeMessage(input, session.id); if(!message.text) return null; const exists=session.messages.some(m=>m.id===message.id || hash(`${m.role}:${m.text}`)===hash(`${message.role}:${message.text}`)); if(!exists) session.messages.push(message); session.updatedAt=message.createdAt; if(message.role==="user" && session.title==="AHA Chat session") session.title=message.text.slice(0,80); replaceSession(session); return message; }
  function updateMessage(messageId, patch){ let found=null; const sessions=loadSessions().map(s=>{ const idx=s.messages.findIndex(m=>m.id===messageId); if(idx>=0){ s.messages[idx]=normalizeMessage({...s.messages[idx], ...obj(patch), id:messageId}, s.id); s.updatedAt=now(); found=s.messages[idx]; } return s; }); saveSessions(sessions); return found; }
  function appendUserMessage(textValue, meta={}){ return addMessage({ role:"user", text:textValue, meta }); }
  function appendAssistantMessage(textValue, meta={}){ return addMessage({ role:"assistant", text:textValue, meta, answerPackageId:meta.answerPackageId, answerEvaluationId:meta.answerEvaluationId, retrievalSummary:meta.retrievalSummary, concepts:meta.concepts, tags:meta.tags, project:meta.project, intent:meta.intent }); }
  function attachAnswerPackage(messageId, answerPackage){ const ref=compact(answerPackage); return updateMessage(messageId,{ answerPackageId:ref.id, meta:{ answerPackage:ref } }); }
  function attachAnswerEvaluation(messageId, evaluation){ const ref=compact(evaluation); return updateMessage(messageId,{ answerEvaluationId:ref.id, meta:{ answerEvaluation:ref } }); }
  function collectChatStats(){ const sessions=loadSessions(); const messages=sessions.flatMap(s=>s.messages||[]); return { sessions:sessions.length, messages:messages.length, userMessages:messages.filter(m=>m.role==="user").length, assistantMessages:messages.filter(m=>m.role==="assistant").length, withAnswerPackage:messages.filter(m=>m.answerPackageId||m.meta?.answerPackage).length, withEvaluation:messages.filter(m=>m.answerEvaluationId||m.meta?.answerEvaluation).length, lastMessageAt:messages.map(m=>m.createdAt).sort().at(-1)||"" }; }
  function isTechnical(m){ return /^(leser|minnestatus|aha analyserer|klar|source connectors|lagret \d+ signal|personlig kontekst aktiv)/i.test(text(m.text)); }
  function selectMessagesForIntake(options={}){ const min=Number(options.minLength)||32; const seen=new Set(); const skipped=[]; const reasons={empty:0,short:0,technical:0,duplicate:0,lowEvaluation:0}; const items=[]; loadSessions().forEach(s=>arr(s.messages).forEach(m=>{ const body=text(m.text); if(!body){reasons.empty++; skipped.push(m.id); return;} if(isTechnical(m)){reasons.technical++; skipped.push(m.id); return;} if(body.length<min && !m.project && !arr(m.concepts).length){reasons.short++; skipped.push(m.id); return;} const k=hash(`${m.role}:${body}`); if(seen.has(k)){reasons.duplicate++; skipped.push(m.id); return;} seen.add(k); const score=Number(m.meta?.answerEvaluation?.score)||0; const valuable=m.role==="user" || score>=70 || m.answerPackageId || m.answerEvaluationId || m.project || arr(m.concepts).length || arr(m.tags).length; if(m.role==="assistant" && score && score<60 && !m.answerPackageId){reasons.lowEvaluation++; skipped.push(m.id); return;} if(valuable) items.push({...m, session:s}); else { reasons.short++; skipped.push(m.id); } })); return { ok:true, items, skipped, reasons }; }
  function buildChatIntakeCandidates(options={}){ const selected=selectMessagesForIntake(options); const items=selected.items.map(({session,...m})=>({ source:"aha_chat", sourceId:m.id, sourceType:"chat_message", title:`AHA Chat: ${m.role} · ${text(m.text).slice(0,70)}`, text:m.text, summary:text(m.text).slice(0,220), language:/[æøå]/i.test(m.text)?"no":"unknown", project:m.project, tags:uniq([...(m.tags||[]), m.role === "assistant" ? "aha-svar" : "brukerbeskjed"]), concepts:uniq(m.concepts), suggestedTargets:[{target:"training_corpus",confidence:.72,reason:"Chatutdrag kan godkjennes som treningsgrunnlag."},{target:"personal_retrieval",confidence:.86,reason:"Chatutdrag kan brukes i personlig retrieval etter godkjenning."},{target:"meta_insights_memory",confidence:.7,reason:"Samtaler kan gi selvinnsikt."}], status:"review", consent:{ useForMemory:true, useForTrainingCorpus:false, useForRetrieval:true, useForStyle:false, useForFineTuning:false }, meta:{ sessionId:m.sessionId, messageId:m.id, role:m.role, createdAt:m.createdAt, answerPackageId:m.answerPackageId, answerEvaluationId:m.answerEvaluationId, privacyNote:"Samtaler brukes ikke som treningsgrunnlag før du har godkjent dem i Data Intake." } })); return { ...selected, items }; }
  global.AHAChatPersistence={ VERSION, STORAGE_KEY, loadSessions, saveSessions, getOrCreateCurrentSession, addMessage, updateMessage, appendUserMessage, appendAssistantMessage, attachAnswerPackage, attachAnswerEvaluation, collectChatStats, selectMessagesForIntake, buildChatIntakeCandidates };
})(typeof window !== "undefined" ? window : globalThis);
