// AHA Data Intake V1 – samlet lokal inngang før Training Corpus.
(function (global) {
  "use strict";
  const STORAGE_KEY = "aha_data_intake_queue_v1";
  const TYPE = "data_intake_item";
  const SOURCES = ["aha_chat","manual","sync_hub","aha_music","history_go","aha_notes","aha_feed","aha_articles","meta_insights","personal_ai"];
  const SOURCE_TYPES = ["chat_message","manual_text","sync_candidate","music_track","artist","playlist","history_go_place","history_go_discovery","note","feed_post","article","meta_summary","answer_evaluation","training_suggestion"];
  const STATUSES = ["new","review","approved","imported","dismissed","archived","failed"];
  const DEFAULT_CONSENT = { useForMemory:true, useForTrainingCorpus:false, useForRetrieval:true, useForStyle:false, useForFineTuning:false, useForHistoryGo:false, useForMusicCanon:false };
  const SOURCE_KEYS = {
    aha_chat:["aha_chat_history_v1","aha_chat_messages_v1","aha_chat_log_v1"],
    sync_hub:["aha_sync_hub_candidates_v1","aha_manual_sync_candidates_v1","aha_sync_candidates_v1"],
    aha_music:["aha_music_library_v1","aha_music_tracks_v1","aha_music_artists_v1","aha_music_playlists_v1"],
    history_go:["aha_historygo_bridge_v1","aha_history_go_discoveries_v1","aha_historygo_discoveries_v1"],
    aha_notes:["aha_notes_v1"], aha_feed:["aha_feed_posts_v1"], aha_articles:["aha_articles_v1"],
    meta_insights:["aha_meta_insights_memory_v1","aha_insight_chamber_v1"], personal_ai:["aha_personal_answer_evaluations_v1","aha_personal_ai_loop_audit_v1"]
  };
  function storage(){ try { return global.localStorage || null; } catch { return null; } }
  function parse(raw, fb){ try { const v=JSON.parse(raw); return v == null ? fb : v; } catch { return fb; } }
  function arr(v){ return Array.isArray(v) ? v : []; }
  function obj(v){ return v && typeof v === "object" && !Array.isArray(v) ? v : {}; }
  function text(v){ return String(v ?? "").trim(); }
  function uniq(v){ const seen=new Set(); return (Array.isArray(v)?v:(typeof v==="string"?v.split(","):[])).map(x=>text(x?.label||x?.name||x)).filter(Boolean).filter(x=>{const k=x.toLowerCase(); if(seen.has(k)) return false; seen.add(k); return true;}); }
  function id(prefix="intake"){ return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`; }
  function now(){ return new Date().toISOString(); }
  function hash(value){ const s=text(value).replace(/\s+/g," ").toLowerCase(); let h=5381; for(let i=0;i<s.length;i++) h=((h<<5)+h+s.charCodeAt(i))>>>0; return `t${h.toString(36)}_${s.length}`; }
  function language(t){ const s=text(t).toLowerCase(); if(!s) return "unknown"; if(/[æøå]|\b(og|jeg|ikke|som|det|på|med|prosjekt)\b/.test(s)) return "no"; if(/\b(the|and|this|project|with|knowledge)\b/.test(s)) return "en"; return "unknown"; }
  function consent(c){ const out={...DEFAULT_CONSENT}; Object.keys(out).forEach(k=>{ if(Object.prototype.hasOwnProperty.call(obj(c),k)) out[k]=obj(c)[k]===true; }); return out; }
  function normalizeSource(s){ const v=text(s); return SOURCES.includes(v)?v:"manual"; }
  function normalizeSourceType(s, source){ const v=text(s); if(SOURCE_TYPES.includes(v)) return v; if(source==="aha_chat") return "chat_message"; if(source==="aha_music") return "music_track"; if(source==="history_go") return "history_go_discovery"; return "manual_text"; }
  function summarize(srcText, srcSummary){ return text(srcSummary) || text(srcText).replace(/\s+/g," ").slice(0,220); }
  function normalizeIntakeItem(input){ const s=obj(input); const created=s.createdAt||s.created_at||now(); const source=normalizeSource(s.source); const sourceType=normalizeSourceType(s.sourceType||s.source_type, source); const body=text(s.text||s.body||s.content||s.message||s.description); const item={ id:text(s.id)||id(), type:TYPE, source, sourceId:text(s.sourceId||s.source_id||s.id), sourceType, title:text(s.title||s.name)||body.slice(0,80)||"Uten tittel", text:body, summary:summarize(body,s.summary), language:text(s.language)||language(body), project:text(s.project), tags:uniq(s.tags), concepts:uniq(s.concepts), entities:uniq(s.entities), linkedObjects:arr(s.linkedObjects||s.linked_objects), suggestedTargets:arr(s.suggestedTargets||s.suggested_targets), status:STATUSES.includes(text(s.status))?text(s.status):"new", consent:consent(s.consent), priority:Number(s.priority)||0, createdAt:created, updatedAt:s.updatedAt||s.updated_at||created, importedAt:s.importedAt||"", dismissedAt:s.dismissedAt||"", meta:obj(s.meta) } ; item.suggestedTargets = item.suggestedTargets.length ? item.suggestedTargets : suggestTargets(item); return item; }
  function loadAllQueue(){ return arr(parse(storage()?.getItem(STORAGE_KEY)||"[]",[])).map(normalizeIntakeItem); }
  function loadQueue(){ return loadAllQueue().filter(i=>!["dismissed","archived"].includes(i.status)); }
  function dedupeQueue(items){ const seen=new Set(); const out=[]; arr(items).map(normalizeIntakeItem).forEach(i=>{ const k=i.sourceId?`${i.source}:${i.sourceId}`:(i.text?`${i.source}:${hash(i.text)}`:`${i.source}:${i.sourceType}:${i.title.toLowerCase()}`); if(seen.has(k)) return; seen.add(k); out.push(i); }); return out; }
  function saveQueue(items){ const q=dedupeQueue(arr(items)).map(i=>normalizeIntakeItem(i)); try{ storage()?.setItem(STORAGE_KEY,JSON.stringify(q)); }catch{} return q; }
  function addIntakeItem(input){ const item=normalizeIntakeItem(input); const all=loadAllQueue(); all.unshift(item); saveQueue(all); return item; }
  function updateIntakeItem(itemId, patch){ const all=loadAllQueue(); const ix=all.findIndex(i=>i.id===itemId); if(ix<0) return null; all[ix]=normalizeIntakeItem({...all[ix],...obj(patch),id:all[ix].id,createdAt:all[ix].createdAt,updatedAt:now()}); saveQueue(all); return all[ix]; }
  function markStatus(itemId,status){ if(!STATUSES.includes(text(status))) return null; return updateIntakeItem(itemId,{status}); }
  function setConsent(itemId, consentPatch){ const item=loadAllQueue().find(i=>i.id===itemId); return item ? updateIntakeItem(itemId,{consent:{...item.consent,...obj(consentPatch)}}) : null; }
  function dismissItem(itemId){ return updateIntakeItem(itemId,{status:"dismissed",dismissedAt:now()}); }
  function archiveItem(itemId){ return updateIntakeItem(itemId,{status:"archived"}); }
  function hasText(i){ return Boolean(text(i.text||i.summary)); }
  function suggestTargets(input){ const i={...obj(input), consent:consent(input?.consent)}; const out=[]; const add=(target,confidence,reason)=>{ if(!out.some(x=>x.target===target)) out.push({target,confidence,reason}); } ; const st=text(i.sourceType); const hay=`${i.title||""} ${i.text||""} ${i.summary||""} ${arr(i.tags).join(" ")} ${arr(i.concepts).join(" ")}`.toLowerCase(); if(hasText(i) && (i.project||arr(i.concepts).length||hay.length>80)) add("training_corpus",0.82,"Tekst med prosjekt, begreper eller nok innhold kan bli corpus."); if(/confirmed|self insight|selvinnsikt|bekreftet|viktig/.test(hay)||i.source==="meta_insights") add("meta_insights_memory",0.76,"Bekreftet innsikt kan bli minne."); if(["music_track","artist","playlist"].includes(st)||i.source==="aha_music") add("aha_music_canon",0.88,"Musikkdata kan bli Music Canon."); if(["artist","history_go_place","history_go_discovery"].includes(st)||i.source==="history_go") add("history_go_discovery",0.82,"Oppdagelse/sted/artist kan kobles til History Go."); if(hasText(i)&&i.status==="approved"&&i.consent.useForRetrieval) add("personal_retrieval",0.78,"Godkjent tekst med retrieval-samtykke kan indekseres."); if(/stil|tone|voice|skrivestil|style/.test(hay)) add("training_corpus",0.72,"Tekst med stilpreg kan brukes som stilgrunnlag."); if(i.source==="sync_hub") add("sync_hub_review",0.7,"Sync-kandidat bør vurderes."); return out; }
  function collectIntakeStats(){ const all=loadAllQueue(); const s={total:all.length,new:0,review:0,approved:0,imported:0,dismissed:0,archived:0,failed:0,bySource:{},bySourceType:{},trainingReady:0,retrievalReady:0,fineTuningAllowed:0,historyGoReady:0,musicCanonReady:0}; all.forEach(i=>{ s[i.status]=(s[i.status]||0)+1; s.bySource[i.source]=(s.bySource[i.source]||0)+1; s.bySourceType[i.sourceType]=(s.bySourceType[i.sourceType]||0)+1; if(i.status==="approved"&&i.consent.useForTrainingCorpus&&hasText(i)) s.trainingReady++; if(i.status==="approved"&&i.consent.useForRetrieval&&hasText(i)) s.retrievalReady++; if(i.consent.useForFineTuning) s.fineTuningAllowed++; if(i.consent.useForHistoryGo) s.historyGoReady++; if(i.consent.useForMusicCanon) s.musicCanonReady++; }); return s; }
  function extractRecords(source,key,data){ let list=Array.isArray(data)?data:arr(data?.items||data?.records||data?.messages||data?.tracks||data?.artists||data?.playlists||data?.feedback||data?.evaluations); if(!list.length && obj(data).id) list=[data]; return list.map(r=>recordToItem(source,key,r)).filter(Boolean); }
  function recordToItem(source,key,r){ const o=obj(r); if(!Object.keys(o).length) return null; const sourceType = source==="aha_chat"?"chat_message":source==="sync_hub"?"sync_candidate":source==="aha_music"?(key.includes("artist")?"artist":key.includes("playlist")?"playlist":"music_track"):source==="history_go"?(String(o.type||"").includes("place")?"history_go_place":"history_go_discovery"):source==="aha_notes"?"note":source==="aha_feed"?"feed_post":source==="aha_articles"?"article":source==="meta_insights"?"meta_summary":source==="personal_ai"?(o.trainingSuggestion||o.training_suggestion?"training_suggestion":"answer_evaluation"):"manual_text"; return {source, sourceId:o.id||o.sourceId||`${key}:${hash(JSON.stringify(o).slice(0,500))}`, sourceType, title:o.title||o.name||o.artist||o.question||sourceType, text:o.text||o.body||o.content||o.message||o.summary||o.answer||o.trainingSuggestion||o.training_suggestion||o.notes||"", summary:o.summary||o.description||"", project:o.project, tags:o.tags, concepts:o.concepts, entities:o.entities, meta:{storageKey:key, rawType:o.type||""}}; }
  function scanExistingSources(){ const before=loadAllQueue().length; const candidates=[]; Object.entries(SOURCE_KEYS).forEach(([source,keys])=>keys.forEach(key=>{ const raw=storage()?.getItem(key); if(!raw) return; extractRecords(source,key,parse(raw,null)).forEach(i=>candidates.push(i)); })); const merged=saveQueue([...loadAllQueue(),...candidates]); const bySource={}; candidates.forEach(i=>{bySource[i.source]=(bySource[i.source]||0)+1;}); return { ok:true, added:Math.max(0,merged.length-before), skipped:Math.max(0,candidates.length-Math.max(0,merged.length-before)), total:merged.length, bySource }; }
  function approveForTrainingCorpus(itemId){ return setConsent(itemId,{useForTrainingCorpus:true}) && markStatus(itemId,"approved"); }
  function importApprovedToTrainingCorpus(){ const api=global.AHATrainingCorpus; const all=loadAllQueue(); const res={ok:Boolean(api?.addCorpusItem),imported:0,skipped:0,failed:0}; if(!api?.addCorpusItem){ res.skipped=all.length; return res; } all.forEach(i=>{ if(!(i.status==="approved"&&i.consent.useForTrainingCorpus&&hasText(i))){res.skipped++; return;} try{ const added=api.addCorpusItem({source:i.source,sourceId:i.id,sourceType:i.sourceType,title:i.title,text:i.text||i.summary,language:i.language,project:i.project,tags:i.tags,concepts:i.concepts,status:"raw",consent:{useForMemory:i.consent.useForMemory,useForTrainingExamples:true,useForFineTuning:i.consent.useForFineTuning,useForStyle:i.consent.useForStyle,useForKnowledge:i.consent.useForRetrieval},meta:{dataIntakeId:i.id}}); if(added){ updateIntakeItem(i.id,{status:"imported",importedAt:now()}); res.imported++; } else res.failed++; }catch{res.failed++;} }); return res; }
  function buildIntakeSummary(){ const s=collectIntakeStats(); const topSources=Object.entries(s.bySource).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([source,count])=>({source,count})); const nextAction=s.review?"Godkjenn nye intake items.":s.approved?"Importer godkjent materiale til Training Corpus.":"Skann AHA-kilder eller legg inn tekst manuelt."; return {available:true,total:s.total,reviewCount:s.review+s.new,approvedCount:s.approved,importedCount:s.imported,topSources,nextAction}; }
  global.AHADataIntake={STORAGE_KEY,DEFAULT_CONSENT,SOURCE_KEYS,loadQueue,loadAllQueue,saveQueue,normalizeIntakeItem,addIntakeItem,updateIntakeItem,markStatus,setConsent,dismissItem,archiveItem,dedupeQueue,collectIntakeStats,suggestTargets,scanExistingSources,approveForTrainingCorpus,importApprovedToTrainingCorpus,buildIntakeSummary};
})(typeof window !== "undefined" ? window : globalThis);
