// Dashboard for AHA Data Intake V1.
(function (global) {
  "use strict";
  const doc = global.document;
  let sourceFilter = "all";
  function $(id){ return doc ? doc.getElementById(id) : null; }
  function api(){ return global.AHADataIntake; }
  function esc(v){ return String(v ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;"); }
  function short(v,n=220){ const s=String(v??"").replace(/\s+/g," ").trim(); return s.length>n?`${s.slice(0,n-1)}…`:s; }
  function set(id,val){ const el=$(id); if(el) el.textContent=String(val); }
  function sourceLabel(source){ return ({aha_chat:"Chat",sync_hub:"Sync Hub",aha_music:"Music",history_go:"History Go",personal_ai:"Personal AI",manual:"Manual"})[source]||source; }
  function renderStats(){ const s=api()?.collectIntakeStats?.()||{}; ["total","new","review","approved","imported","trainingReady","retrievalReady","fineTuningAllowed"].forEach(k=>set(`intake-stat-${k}`,s[k]||0)); }
  function visibleItems(){ const items=api()?.loadQueue?.()||[]; if(sourceFilter==="all") return items; const map={chat:"aha_chat",sync:"sync_hub",music:"aha_music",history:"history_go",personal:"personal_ai",manual:"manual"}; return items.filter(i=>i.source===map[sourceFilter]); }
  function consentFlags(i){ const c=i.consent||{}; return Object.entries({useForMemory:"memory",useForTrainingCorpus:"training",useForRetrieval:"retrieval",useForStyle:"style",useForFineTuning:"fine-tune",useForHistoryGo:"history",useForMusicCanon:"music canon"}).filter(([k])=>c[k]).map(([,v])=>v); }
  function renderList(){ const mount=$("intake-list"); if(!mount) return; const items=visibleItems(); if(!items.length){ mount.innerHTML='<p class="aha-training-empty">Data Intake er tomt. Skann AHA-kilder eller legg inn tekst manuelt.</p>'; return; } mount.innerHTML=items.map(i=>`<article class="aha-panel aha-training-item" data-intake-id="${esc(i.id)}"><header class="aha-training-item-header"><h3>${esc(i.title)}</h3><span class="aha-status-badge">${esc(i.status)}</span></header><p class="module-meta">${esc(sourceLabel(i.source))} · ${esc(i.sourceType)}</p><p>${esc(short(i.summary||i.text))}</p><p class="module-meta"><strong>Targets:</strong> ${esc((i.suggestedTargets||[]).map(t=>`${t.target} (${Math.round((t.confidence||0)*100)}%)`).join(", ")||"ingen")}</p><p class="aha-training-consent"><strong>Consent:</strong> ${esc(consentFlags(i).join(", ")||"ingen")}</p><div class="aha-training-actions"><button data-intake-approve="${esc(i.id)}">Godkjenn</button><button data-intake-training="${esc(i.id)}">Send til Training Corpus</button><button data-intake-consent="useForRetrieval" data-intake-id="${esc(i.id)}">${i.consent?.useForRetrieval?"✓ ":""}Tillat retrieval</button><button data-intake-consent="useForStyle" data-intake-id="${esc(i.id)}">${i.consent?.useForStyle?"✓ ":""}Tillat stil</button><button data-intake-consent="useForHistoryGo" data-intake-id="${esc(i.id)}">${i.consent?.useForHistoryGo?"✓ ":""}Tillat History Go</button><button data-intake-consent="useForMusicCanon" data-intake-id="${esc(i.id)}">${i.consent?.useForMusicCanon?"✓ ":""}Tillat Music Canon</button><button data-intake-archive="${esc(i.id)}">Arkiver</button><button data-intake-dismiss="${esc(i.id)}">Dismiss</button></div></article>`).join(""); }
  function renderSourceConnectors(){ const api=global.AHASourceConnectors; const status=api?.collectConnectorStatus?.(); if(!status) return; set("source-connectors-active",status.active||0); set("source-connectors-planned",status.planned||0); set("source-connectors-missing",status.missing||0); const last=global.__ahaSourceConnectorLastScan||{}; set("source-connectors-scanned",last.totalScanned||0); set("source-connectors-added",last.totalAdded||0); set("source-connectors-warnings",(last.warnings||[]).length||0); const mount=$("source-connectors-list"); if(mount){ mount.innerHTML=(status.connectors||[]).map(c=>`<article class="aha-panel aha-training-item"><header class="aha-training-item-header"><h3>${esc(c.title)}</h3><span class="aha-status-badge">${esc(c.status)}</span></header><p class="module-meta">${esc(c.source)} · ${esc(c.reason||"")}</p><p class="module-meta">Items: ${esc(c.itemCount||0)}${c.source==="aha_chat" ? " · Chat candidates: "+esc(c.itemCount||0) : ""} · Last scanned: ${esc(c.lastScannedAt||"aldri")}</p></article>`).join(""); } doc?.querySelectorAll?.("[data-source-scan]").forEach(btn=>{ const src=btn.getAttribute("data-source-scan"); if(src==="all") return; const c=(status.connectors||[]).find(x=>x.source===src); btn.disabled=!c||c.status!=="active"; btn.title=c?c.status:"missing"; }); }
  function renderAll(){ renderStats(); renderSourceConnectors(); renderList(); }
  function message(t){ const el=$("intake-message"); if(el) el.textContent=t||""; }
  function bind(){ if(!doc) return; doc.querySelectorAll?.("[data-source-scan]").forEach(btn=>btn.addEventListener("click",()=>{ const src=btn.getAttribute("data-source-scan"); const api=global.AHASourceConnectors; if(!api) return; const r=src==="all"?api.scanAllSources():api.scanSource(src); global.__ahaSourceConnectorLastScan={ totalScanned:src==="all"?(r.results||[]).reduce((n,x)=>n+(x.total||0),0):(r.total||0), totalAdded:r.totalAdded ?? r.added ?? 0, warnings:r.warnings||[] }; message(`Source Connectors: ${global.__ahaSourceConnectorLastScan.totalAdded} lagt til.`); renderAll(); })); $("intake-scan-btn")?.addEventListener("click",()=>{ const r=api()?.scanExistingSources?.()||{}; message(`Skann ferdig: ${r.added||0} lagt til, ${r.skipped||0} hoppet over.`); renderAll(); }); $("intake-import-btn")?.addEventListener("click",()=>{ const r=api()?.importApprovedToTrainingCorpus?.()||{}; message(`Import: ${r.imported||0} importert, ${r.skipped||0} hoppet over, ${r.failed||0} feilet.`); renderAll(); }); $("intake-source-filter")?.addEventListener("change",e=>{ sourceFilter=e.target.value; renderList(); }); $("intake-manual-form")?.addEventListener("submit",e=>{ e.preventDefault(); const form=e.currentTarget; const item=api()?.addIntakeItem?.({source:"manual",sourceType:"manual_text",status:"review",title:form.title.value,text:form.text.value,project:form.project.value,tags:form.tags.value}); if(item){ form.reset(); message("Manual text lagt til i Data Intake."); renderAll(); } }); $("intake-list")?.addEventListener("click",e=>{ const t=e.target; if(!(t instanceof global.HTMLElement)) return; const id=t.getAttribute("data-intake-id")||t.getAttribute("data-intake-approve")||t.getAttribute("data-intake-training")||t.getAttribute("data-intake-archive")||t.getAttribute("data-intake-dismiss"); if(!id) return; const a=api(); if(t.hasAttribute("data-intake-approve")) a.markStatus(id,"approved"); else if(t.hasAttribute("data-intake-training")) a.approveForTrainingCorpus(id); else if(t.hasAttribute("data-intake-archive")) a.archiveItem(id); else if(t.hasAttribute("data-intake-dismiss")) a.dismissItem(id); else { const k=t.getAttribute("data-intake-consent"); const item=a.loadAllQueue().find(x=>x.id===id); if(k&&item) a.setConsent(id,{[k]:!item.consent?.[k]}); } renderAll(); }); }
  function init(){ bind(); renderAll(); }
  global.AHADataIntakeDashboard={init,renderAll,renderStats,renderList,renderSourceConnectors}; if(doc){ if(doc.readyState==="loading") doc.addEventListener("DOMContentLoaded",init); else init(); }
})(typeof window !== "undefined" ? window : globalThis);
