// AHA Knowledge Map V1 – avledet, lokal graf over kuratert AHA-kunnskap.
(function(global){"use strict";
const STORAGE_KEY="aha_knowledge_map_v1", VERSION="v1";
const NODE_TYPES=["project","concept","theme","source","intake_item","curation_item","training_corpus_item","training_example","memory_claim","person","place","artist","track","playlist","history_go_object","music_canon_object"];
function pipelineBoundaryMeta(extra = {}) { return { source_app: "aha", origin_app: extra.origin_app || "aha_knowledge_pipeline", local_only: true, manual_review_required: true, candidate_only: extra.candidate_only ?? false, approval_required: true, auto_training_enabled: false, fine_tuning_enabled: false, backend_enabled: false, echonet_shared: false, sync_enabled: false, historygo_writeback_enabled: false, writes_to_insight_chamber: false, canonical_engine: false, ...extra }; }
function isUnavailableRecord(record) { return Boolean(record?.deleted_at || record?.deletedAt || record?.archived === true || record?.status === "archived" || record?.status === "dismissed"); }
function storage(){try{return global.localStorage||null;}catch{return null;}} function parse(r,f){try{const v=JSON.parse(r);return v??f;}catch{return f;}}
function arr(v){return Array.isArray(v)?v:(typeof v==="string"?v.split(","):[]);} function obj(v){return v&&typeof v==="object"&&!Array.isArray(v)?v:{}} function text(v){return String(v??"").trim();}
function uniq(v){const seen=new Set();return arr(v).map(x=>text(x?.label||x?.name||x?.title||x)).filter(Boolean).filter(x=>{const k=norm(x);if(seen.has(k))return false;seen.add(k);return true;});}
function now(){return new Date().toISOString();} function norm(v){return text(v).toLowerCase().replace(/[^a-z0-9æøå]+/gi," ").replace(/\s+/g," ").trim();}
function hash(v){const s=norm(v);let h=5381;for(let i=0;i<s.length;i++)h=((h<<5)+h+s.charCodeAt(i))>>>0;return h.toString(36);} function id(p,...bits){return `${p}_${hash(bits.filter(Boolean).join(":"))||Math.random().toString(36).slice(2,8)}`;}
function node(input){const s=obj(input), t=NODE_TYPES.includes(s.nodeType)?s.nodeType:"concept"; const created=s.createdAt||now(); const existingMeta=obj(s.meta); return {id:text(s.id)||id("kmn",t,s.source,s.sourceId,s.label),type:"knowledge_map_node",local_only:true,derived_graph_node:true,canonical_truth:false,source_trace_required:true,echonet_shared:false,sync_enabled:false,backend_enabled:false,nodeType:t,label:text(s.label||s.title)||"Uten tittel",title:text(s.title||s.label),summary:text(s.summary),source:text(s.source),sourceId:text(s.sourceId),sourceType:text(s.sourceType),project:text(s.project),concepts:uniq(s.concepts),tags:uniq(s.tags),entities:uniq(s.entities),weight:Number(s.weight)||1,status:text(s.status),createdAt:created,updatedAt:s.updatedAt||created,meta:{...existingMeta,...pipelineBoundaryMeta({origin_app:"aha_knowledge_map",object_type:"knowledge_map_node",derived_graph_node:true,canonical_truth:false})}};}
function edge(input){const s=obj(input), created=s.createdAt||now(); const existingMeta=obj(s.meta); return {id:text(s.id)||id("kme",s.from,s.to,s.relationType),type:"knowledge_map_edge",local_only:true,derived_graph_edge:true,canonical_truth:false,source_trace_required:true,echonet_shared:false,sync_enabled:false,backend_enabled:false,from:text(s.from),to:text(s.to),relationType:text(s.relationType||"related_to"),label:text(s.label||s.relationType||"related_to"),weight:Number(s.weight)||1,confidence:Number.isFinite(Number(s.confidence))?Number(s.confidence):0.7,source:text(s.source),sourceId:text(s.sourceId),createdAt:created,updatedAt:s.updatedAt||created,meta:{...existingMeta,...pipelineBoundaryMeta({origin_app:"aha_knowledge_map",object_type:"knowledge_map_node",derived_graph_node:true,canonical_truth:false})}};}
function itemTitle(i){return text(i.title||i.name||i.input||i.claimText||i.summary||i.text).slice(0,120)||"Uten tittel";} function itemSummary(i){return text(i.summary||i.output||i.text||i.claimText||i.description).slice(0,260);} function sourceId(i){return text(i.id||i.sourceId||i.corpusItemId||i.claimId||itemTitle(i));}
function extractKeywords(i){const hay=`${i.title||""} ${i.summary||""} ${i.text||""} ${i.input||""} ${i.output||""}`.toLowerCase();return uniq((hay.match(/\b[A-ZÆØÅa-zæøå][A-ZÆØÅa-zæøå0-9-]{4,}\b/g)||[]).slice(0,8));}
function buildNodesFromIntake(items){return arr(items).map(i=>node({nodeType:i.sourceType==="artist"?"artist":i.sourceType==="playlist"?"playlist":i.sourceType==="music_track"?"track":i.source?.includes("history")?"history_go_object":"intake_item",label:itemTitle(i),title:itemTitle(i),summary:itemSummary(i),source:"data_intake",sourceId:sourceId(i),sourceType:i.sourceType,project:i.project,concepts:i.concepts,tags:i.tags,entities:i.entities,weight:1,status:i.status,createdAt:i.createdAt,updatedAt:i.updatedAt,meta:{linkedObjects:arr(i.linkedObjects),rawSource:i.source}}));}
function buildNodesFromCuration(items){return arr(items).map(i=>node({nodeType:"curation_item",label:itemTitle(i),title:itemTitle(i),summary:itemSummary(i),source:"knowledge_curation",sourceId:sourceId(i),sourceType:"knowledge_curation_item",project:i.project,concepts:i.concepts,tags:i.tags,entities:i.entities,weight:i.priority==="high"?2:1,status:i.status,createdAt:i.createdAt,updatedAt:i.updatedAt,meta:{theme:i.theme,sourceItemIds:arr(i.sourceItemIds),suggestedTargets:arr(i.suggestedTargets)}}));}
function buildNodesFromTrainingCorpus(items){return arr(items).map(i=>node({nodeType:"training_corpus_item",label:itemTitle(i),title:itemTitle(i),summary:itemSummary(i),source:"training_corpus",sourceId:sourceId(i),sourceType:i.sourceType,project:i.project,concepts:i.concepts,tags:i.tags,weight:i.status==="approved"?2:1,status:i.status,createdAt:i.createdAt,updatedAt:i.updatedAt,meta:{source:i.source,sourceId:i.sourceId,curationItemId:i.meta?.curationItemId,dataIntakeId:i.meta?.dataIntakeId}}));}
function buildNodesFromTrainingExamples(items){return arr(items).map(i=>node({nodeType:"training_example",label:itemTitle(i),title:itemTitle(i),summary:itemSummary(i),source:"training_examples",sourceId:sourceId(i),sourceType:i.taskType,concepts:i.labels,tags:i.labels,weight:i.status==="approved"?2:1,status:i.status,createdAt:i.createdAt,updatedAt:i.updatedAt,meta:{corpusItemId:i.corpusItemId}}));}
function buildNodesFromMemory(pack){const p=obj(pack), claims=[...arr(p.confirmed_claims).map(x=>({claimText:x,status:"confirmed"})),...arr(p.important_claims).map(x=>({claimText:x,status:"important"}))]; return claims.map(i=>node({nodeType:"memory_claim",label:i.claimText,title:i.claimText,summary:i.claimText,source:"meta_insights_memory",sourceId:i.claimText,status:i.status,project:"",concepts:extractKeywords(i),weight:i.status==="important"?2:1,meta:{activeProjects:arr(p.active_self_model?.active_projects)}}));}
function buildProjectNodes(items){let vals=[];arr(items).forEach(i=>{if(i.project)vals.push(i.project); if(i.nodeType==="curation_item"&&i.meta?.theme)vals.push(i.project); arr(i.activeProjects||i.meta?.activeProjects).forEach(x=>vals.push(x));}); return uniq(vals).map(p=>node({nodeType:"project",label:p,title:p,source:"knowledge_map",sourceId:`project:${norm(p)}`,project:p,weight:2}));}
function buildConceptNodes(items){let vals=[];arr(items).forEach(i=>{vals.push(...arr(i.concepts),...arr(i.tags)); if(i.theme)vals.push(i.theme); if(i.meta?.theme)vals.push(i.meta.theme); vals.push(...extractKeywords(i));}); return uniq(vals).map(c=>node({nodeType:"concept",label:c,title:c,source:"knowledge_map",sourceId:`concept:${norm(c)}`,concepts:[c]}));}
function buildEntityNodes(items){let vals=[];arr(items).forEach(i=>{vals.push(...arr(i.entities)); arr(i.linkedObjects||i.meta?.linkedObjects).forEach(o=>vals.push(o.name||o.title||o.label||o.id));}); return uniq(vals).map(e=>node({nodeType:/\b(oslo|bergen|sted|place)\b/i.test(e)?"place":/\b(artist|band)\b/i.test(e)?"artist":"person",label:e,title:e,source:"knowledge_map",sourceId:`entity:${norm(e)}`,entities:[e]}));}
function index(nodes,type,label){const k=norm(label);return arr(nodes).find(n=>(!type||n.nodeType===type)&&norm(n.label)===k);} function sourceNode(nodes,source,idv){return arr(nodes).find(n=>n.source===source&&n.sourceId===text(idv));}
function buildEdges(nodes, sourceItems={}){const out=[]; const add=(from,to,rel,label,src,srcId,conf=.75)=>{if(from&&to&&from!==to)out.push(edge({from,to,relationType:rel,label,source:src,sourceId:srcId,confidence:conf}));}; arr(nodes).filter(n=>/_item$|example|memory_claim|track|artist/.test(n.nodeType)).forEach(n=>{const p=n.project&&index(nodes,"project",n.project); if(p)add(n.id,p.id,"belongs_to_project","belongs to project",n.source,n.sourceId); arr(n.concepts).forEach(c=>{const cn=index(nodes,"concept",c); if(cn)add(n.id,cn.id,"has_concept","has concept",n.source,n.sourceId);}); arr(n.tags).forEach(c=>{const cn=index(nodes,"concept",c); if(cn)add(n.id,cn.id,"has_concept","tagged as concept",n.source,n.sourceId,.65);}); arr(n.entities).forEach(e=>{const en=index(nodes,null,e); if(en)add(n.id,en.id,"mentions_entity","mentions entity",n.source,n.sourceId,.65);}); if(n.nodeType==="training_example"&&n.meta?.corpusItemId){const c=sourceNode(nodes,"training_corpus",n.meta.corpusItemId); if(c)add(n.id,c.id,"training_example_for","training example for",n.source,n.sourceId,.9);} if(n.nodeType==="training_corpus_item"){const c=n.meta?.curationItemId&&sourceNode(nodes,"knowledge_curation",n.meta.curationItemId); const d=n.meta?.dataIntakeId&&sourceNode(nodes,"data_intake",n.meta.dataIntakeId); if(c)add(n.id,c.id,"derived_from","derived from curation",n.source,n.sourceId,.9); if(d)add(n.id,d.id,"derived_from","derived from intake",n.source,n.sourceId,.85);} if(n.nodeType==="curation_item")arr(n.meta?.sourceItemIds).forEach(sid=>{const i=sourceNode(nodes,"data_intake",sid); if(i)add(n.id,i.id,"curated_from","curated from",n.source,n.sourceId,.9);}); if(n.nodeType==="track")arr(n.entities).forEach(e=>{const a=index(nodes,"artist",e); if(a)add(n.id,a.id,"music_by_artist","music by artist",n.source,n.sourceId,.7);}); if(n.nodeType==="memory_claim")arr(n.concepts).forEach(c=>{const cn=index(nodes,"concept",c); if(cn)add(n.id,cn.id,"memory_about","memory about",n.source,n.sourceId,.7);});}); arr(nodes).filter(n=>n.nodeType==="project").forEach(p=>arr(nodes).filter(n=>n.project===p.label).flatMap(n=>n.concepts).slice(0,8).forEach(c=>{const cn=index(nodes,"concept",c); if(cn)add(p.id,cn.id,"related_to","project concept","knowledge_map",p.sourceId,.55);})); return dedupeEdges(out);}
function dedupeNodes(nodes){const seen=new Map();arr(nodes).map(node).forEach(n=>{const k=n.source&&n.sourceId?`src:${n.source}:${n.sourceId}`:`${n.nodeType}:${norm(n.label)}`; if(!seen.has(k))seen.set(k,n); else {const old=seen.get(k); seen.set(k,{...old,concepts:uniq([...old.concepts,...n.concepts]),tags:uniq([...old.tags,...n.tags]),entities:uniq([...old.entities,...n.entities]),weight:Math.max(old.weight,n.weight),summary:old.summary||n.summary});}});return [...seen.values()];}
function dedupeEdges(edges){const seen=new Map();arr(edges).map(edge).filter(e=>e.from&&e.to).forEach(e=>{const k=`${e.from}:${e.to}:${e.relationType}`; if(!seen.has(k))seen.set(k,e); else seen.set(k,{...seen.get(k),weight:Math.max(seen.get(k).weight,e.weight),confidence:Math.max(seen.get(k).confidence,e.confidence)});});return [...seen.values()];}
function collectMapStats(map){const nodes=arr(map.nodes), edges=arr(map.edges); const byNodeType={}, byRelationType={}; nodes.forEach(n=>byNodeType[n.nodeType]=(byNodeType[n.nodeType]||0)+1); edges.forEach(e=>byRelationType[e.relationType]=(byRelationType[e.relationType]||0)+1); const connected=new Set(edges.flatMap(e=>[e.from,e.to])); const denseProjects=nodes.filter(n=>n.nodeType==="project").map(p=>({id:p.id,label:p.label,count:edges.filter(e=>e.from===p.id||e.to===p.id).length})).sort((a,b)=>b.count-a.count).slice(0,5); return {nodes:nodes.length,edges:edges.length,byNodeType,byRelationType,projects:byNodeType.project||0,concepts:byNodeType.concept||0,themes:byNodeType.theme||0,sources:byNodeType.source||0,people:byNodeType.person||0,places:byNodeType.place||0,artists:byNodeType.artist||0,tracks:byNodeType.track||0,isolatedNodes:nodes.filter(n=>!connected.has(n.id)).length,denseProjects};}
function buildKnowledgeMap(options={}){const intake=(global.AHADataIntake?.loadQueue?.()||[]).filter(i=>!isUnavailableRecord(i)), curation=(global.AHAKnowledgeCuration?.loadCurationItems?.()||[]).filter(i=>!isUnavailableRecord(i)), corpus=(global.AHATrainingCorpus?.loadCorpus?.()||[]).filter(i=>!isUnavailableRecord(i)), examples=(global.AHATrainingExamples?.loadExamples?.()||[]).filter(i=>!isUnavailableRecord(i)), memory=global.AHAMetaInsightsMemory?.buildMemoryPack?.()||{}; let base=[...buildNodesFromIntake(intake),...buildNodesFromCuration(curation),...buildNodesFromTrainingCorpus(corpus),...buildNodesFromTrainingExamples(examples),...buildNodesFromMemory(memory)]; let nodes=dedupeNodes([...base,...buildProjectNodes([...base,{activeProjects:memory.active_self_model?.active_projects}]),...buildConceptNodes(base),...buildEntityNodes([...intake,...curation,...base])]); let map={generatedAt:now(),version:VERSION,local_only:true,derived_graph_only:true,read_model_only:true,canonical_truth:false,manual_review_required:true,auto_training_enabled:false,fine_tuning_enabled:false,backend_enabled:false,echonet_shared:false,sync_enabled:false,historygo_writeback_enabled:false,writes_to_insight_chamber:false,meta:pipelineBoundaryMeta({origin_app:"aha_knowledge_map",object_type:"knowledge_map",derived_graph_only:true,canonical_truth:false}),nodes,edges:[],stats:{}}; map.edges=buildEdges(nodes,{intake,curation,corpus,examples,memory}); map.stats=collectMapStats(map); return map;}
function saveKnowledgeMap(map){const out={...obj(map),local_only:true,derived_graph_only:true,read_model_only:true,canonical_truth:false,manual_review_required:true,auto_training_enabled:false,fine_tuning_enabled:false,backend_enabled:false,echonet_shared:false,sync_enabled:false,historygo_writeback_enabled:false,writes_to_insight_chamber:false,meta:{...obj(map).meta,...pipelineBoundaryMeta({origin_app:"aha_knowledge_map",object_type:"knowledge_map",derived_graph_only:true,canonical_truth:false})},nodes:arr(map.nodes).map(node),edges:arr(map.edges).map(edge),stats:map.stats||collectMapStats(map)}; try{storage()?.setItem(STORAGE_KEY,JSON.stringify(out));}catch{} return out;} function loadKnowledgeMap(){return parse(storage()?.getItem(STORAGE_KEY)||"null",null)||{generatedAt:"",version:VERSION,nodes:[],edges:[],stats:collectMapStats({nodes:[],edges:[]})};}
function refreshKnowledgeMap(options={}){return saveKnowledgeMap(buildKnowledgeMap(options));}
function findRelatedNodes(nodeId,options={}){const map=options.map||loadKnowledgeMap(); const depth=Number(options.depth)||1; const start=text(nodeId); const seen=new Set([start]), edgeSet=[]; let frontier=[start]; for(let d=0;d<depth;d++){const next=[]; arr(map.edges).forEach(e=>{if(frontier.includes(e.from)||frontier.includes(e.to)){edgeSet.push(e); const other=frontier.includes(e.from)?e.to:e.from; if(!seen.has(other)){seen.add(other);next.push(other);}}}); frontier=next;} return {node:arr(map.nodes).find(n=>n.id===start)||null,neighbors:arr(map.nodes).filter(n=>seen.has(n.id)&&n.id!==start),edges:dedupeEdges(edgeSet),depth};}
function searchKnowledgeMap(query,options={}){const q=norm(query), map=options.map||loadKnowledgeMap(); if(!q)return {query,results:[],stats:{total:0}}; const results=arr(map.nodes).filter(n=>norm([n.label,n.title,n.summary,n.project,...n.concepts,...n.tags,...n.entities].join(" ")).includes(q)).map(n=>({...n,related:findRelatedNodes(n.id,{map,depth:1}).neighbors.slice(0,5)})); return {query,results,stats:{total:results.length,nodes:arr(map.nodes).length,edges:arr(map.edges).length}};}
function top(nodes,type){return arr(nodes).filter(n=>n.nodeType===type).sort((a,b)=>b.weight-a.weight).slice(0,5).map(n=>({id:n.id,label:n.label,weight:n.weight}));}
function buildKnowledgeMapSummary(){const map=loadKnowledgeMap(); const stats=map.stats||collectMapStats(map); return {available:arr(map.nodes).length>0,nodes:stats.nodes||0,edges:stats.edges||0,projects:stats.projects||0,concepts:stats.concepts||0,topProjects:top(map.nodes,"project"),topConcepts:top(map.nodes,"concept"),nextAction:stats.nodes?"Åpne Knowledge Map for å se prosjekt- og begrepskoblinger.":"Bygg Knowledge Map fra kuratert materiale."};}
global.AHAKnowledgeMap={STORAGE_KEY,VERSION,pipelineBoundaryMeta,isUnavailableRecord,buildKnowledgeMap,saveKnowledgeMap,loadKnowledgeMap,refreshKnowledgeMap,buildNodesFromIntake,buildNodesFromCuration,buildNodesFromTrainingCorpus,buildNodesFromTrainingExamples,buildNodesFromMemory,buildProjectNodes,buildConceptNodes,buildEntityNodes,buildEdges,dedupeNodes,dedupeEdges,collectMapStats,findRelatedNodes,searchKnowledgeMap,buildKnowledgeMapSummary}; if(typeof module!=="undefined"&&module.exports)module.exports=global.AHAKnowledgeMap;
})(typeof window!=="undefined"?window:globalThis);
