// AHA Knowledge Workflow Audit V1 – read-only audit + isolated safe simulation.
(function(global){"use strict";
const VERSION="AHA Knowledge Workflow Audit V1", STORAGE_KEY="aha_knowledge_workflow_audit_v1";
const STAGES=[
  ["chatPersistence","Chat Persistence","AHAChatPersistence"],["sourceConnectors","Source Connectors","AHASourceConnectors"],["dataIntake","Data Intake","AHADataIntake"],["knowledgeWorkbench","Knowledge Workbench","AHAKnowledgeWorkbench"],["knowledgeCuration","Knowledge Curation","AHAKnowledgeCuration"],["knowledgeMap","Knowledge Map","AHAKnowledgeMap"],["graphIntelligence","Knowledge Graph Intelligence","AHAKnowledgeGraphIntelligence"],["trainingCorpus","Training Corpus","AHATrainingCorpus"],["personalAiControl","Personal AI Control","AHAPersonalAiControl"],["retrieval","Retrieval","AHAPersonalRetrieval"],["semanticRetrieval","Semantic Retrieval","AHASemanticRetrieval"],["chatPersonalContext","Chat Personal Context","AHAChatPersonalContext"],["answerComposer","Answer Composer","AHAPersonalAnswerComposer"],["answerEvaluation","Answer Evaluation","AHAPersonalAnswerEvaluation"]
];
const LINKS=[
  ["index.html","knowledge-workbench.html","Home → Workbench"],["knowledge-workbench.html","intake.html","Workbench → Intake"],["knowledge-workbench.html","curation.html","Workbench → Curation"],["knowledge-workbench.html","knowledge-map.html","Workbench → Knowledge Map"],["knowledge-workbench.html","training.html","Workbench → Training"],["knowledge-workbench.html","personal-ai.html","Workbench → Personal AI"],["knowledge-workbench.html","chat.html","Workbench → Chat"],["chat.html","knowledge-workbench.html","Chat → Workbench"],["intake.html","knowledge-workbench.html","Intake → Workbench"],["curation.html","knowledge-workbench.html","Curation → Workbench"],["knowledge-map.html","knowledge-workbench.html","Knowledge Map → Workbench"],["training.html","knowledge-workbench.html","Training → Workbench"],["personal-ai.html","knowledge-workbench.html","Personal AI → Workbench"]
];
const STORAGE_KEYS=["aha_chat_sessions_v1","aha_data_intake_queue_v1","aha_knowledge_curation_v1","aha_knowledge_map_v1","aha_knowledge_graph_intelligence_v1","aha_training_corpus_v1","aha_training_examples_v1","aha_personal_retrieval_index_v1","aha_personal_semantic_index_v1","aha_personal_answer_evaluations_v1","aha_knowledge_workbench_status_v1"];
function arr(v){return Array.isArray(v)?v:[]} function obj(v){return v&&typeof v==="object"&&!Array.isArray(v)?v:{}} function now(o={}){return o.now||new Date().toISOString()} function safe(fn,fb){try{return typeof fn==="function"?fn():fb}catch(e){return fb}} function read(k){try{return global.localStorage?.getItem(k)||null}catch{return null}} function parse(raw){try{return raw?JSON.parse(raw):null}catch(e){return {parseError:String(e&&e.message||e)}}}
function checkStageAvailability(){const stages=STAGES.map(([id,label,globalName])=>{const api=global[globalName]; return {id,label,globalName,available:Boolean(api),missing:!api,notes:api?"Module exposed on window/globalThis.":`Missing window.${globalName}.`};}); return {available:stages.filter(s=>s.available).length,missing:stages.filter(s=>!s.available),stages,notes:stages.filter(s=>!s.available).map(s=>s.notes)};}
function checkPageLinks(){const doc=global.document; const current=doc?.location?.pathname?.split("/").pop(); const checks=LINKS.map(([page,href,label])=>{let available=false,note="Not checked in browser runtime."; if(doc&&(!current||current===page)){available=Boolean(doc.querySelector?.(`a[href=\"${href}\"], a[href^=\"${href}#\"]`)); note=available?"Link found in DOM.":"Link not found in current DOM.";} return {page,href,label,available,note};}); return {ok:checks.every(c=>c.available||c.note==="Not checked in browser runtime."),checks,issues:checks.filter(c=>!c.available&&c.note!=="Not checked in browser runtime.")};}
function checkStorageKeys(){const keys=STORAGE_KEYS.map(key=>{const raw=read(key); const parsed=parse(raw); const type=raw==null?"missing":Array.isArray(parsed)?"array":obj(parsed).parseError?"invalid_json":typeof parsed; const count=Array.isArray(parsed)?parsed.length:Array.isArray(parsed?.items)?parsed.items.length:Array.isArray(parsed?.evaluations)?parsed.evaluations.length:0; return {key,present:raw!=null,type,count,valid:type!=="invalid_json"};}); return {keys,knownKeys:STORAGE_KEYS,invalid:keys.filter(k=>!k.valid),present:keys.filter(k=>k.present).length};}
function checkConsentBoundaries(){const checks=["Chat blir ikke Training Corpus automatisk.","Intake må godkjennes før Training.","Curation må godkjennes før Training.","Graph Intelligence endrer ikke consent.","Workbench page load godkjenner/importerer ikke automatisk.","Memory claims blir ikke confirmed automatisk.","Fine-tuning consent kreves før eksport."].map(label=>({label,ok:true,severity:"info"})); return {ok:true,checks,warnings:[]};}
function buildWorkflowRecommendations(audit={}){const missing=arr(audit.stages?.missing).map(s=>s.id); const r=[]; if(missing.includes("sourceConnectors")||!audit.storage?.present)r.push("Skann Chat til Data Intake."); r.push("Godkjenn intake items før Curation.","Bygg Knowledge Map etter Curation.","Kjør Graph Intelligence etter map refresh.","Send approved curation til Training Corpus.","Bygg retrieval og semantic index etter Training.","Test Chat med kuratert materiale."); return [...new Set(r)];}
function simulateWorkflow(options={}){const warnings=[]; const steps=[]; const add=(id,label,fn)=>{try{const result=fn(); steps.push({id,label,ok:true,result}); return result;}catch(e){steps.push({id,label,ok:false,error:String(e&&e.message||e)}); warnings.push(`${id}: ${String(e&&e.message||e)}`); return null;}}; const t=now(options); const chat=add("chat_message","Opprett chat message",()=>({id:"mock-chat-1",role:"user",text:"AHA bør huske at kunnskapsløypa krever eksplisitt samtykke.",createdAt:t})); const candidate=add("chat_intake_candidate","Bygg chat intake candidate",()=>({id:"mock-intake-1",source:"aha_chat",sourceId:chat.id,sourceType:"chat_message",status:"new",title:"Workflow consent",text:chat.text,tags:["workflow"],concepts:["samtykke"],suggestedTargets:["training_corpus"],consent:{useForTrainingCorpus:false,useForRetrieval:true,useForFineTuning:false}})); const intake=add("data_intake","Legg candidate i Data Intake og godkjenn",()=>({...candidate,status:"approved",consent:{...candidate.consent,useForTrainingCorpus:true}})); const cur=add("curation","Bygg og godkjenn curation item",()=>({id:"mock-curation-1",status:"approved",sourceItemIds:[intake.id],title:intake.title,summary:intake.text,project:"AHA",tags:intake.tags,concepts:intake.concepts,suggestedTargets:intake.suggestedTargets})); const corpus=add("training_corpus","Send til Training Corpus",()=>({id:"mock-corpus-1",status:"approved",title:cur.title,text:cur.summary,project:cur.project,tags:cur.tags,concepts:cur.concepts,consent:{useForKnowledge:true,useForMemory:true,useForFineTuning:false}})); const map=add("knowledge_map","Bygg Knowledge Map",()=>({nodes:[{id:"concept:samtykke",type:"concept",label:"samtykke"},{id:`corpus:${corpus.id}`,type:"training_corpus_item",label:corpus.title}],edges:[{from:`corpus:${corpus.id}`,to:"concept:samtykke",type:"mentions"}]})); const graph=add("graph_intelligence","Analyser Graph Intelligence",()=>({insights:[{id:"mock-insight-1",title:"Samtykke er sentralt",relatedNodeIds:map.nodes.map(n=>n.id)}],suggestedLinks:[{from:map.nodes[0].id,to:map.nodes[1].id,confidence:0.82,reason:"Mock workflow concept link"}]})); add("retrieval","Bygg retrieval index",()=>({items:[corpus],count:1})); add("semantic_retrieval","Bygg semantic index",()=>({items:[{...corpus,vector:{dimensions:["samtykke"],weights:{samtykke:1}}}],count:1})); add("answer_package","Bygg Answer Package",()=>({query:"Hvordan fungerer samtykke?",sources:[corpus.id],answer:"AHA bruker kuratert materiale etter eksplisitt godkjenning."})); add("answer_evaluation","Evaluer local preview",()=>({status:"needs_review",score:0.86,trainingSuggestion:{status:"needs_review"}})); return {ok:steps.every(s=>s.ok),steps,finalStatus:steps.every(s=>s.ok)?"working":"partial",warnings};}
function runWorkflowAudit(options={}){const stages=checkStageAvailability(), links=checkPageLinks(), storage=checkStorageKeys(), consent=checkConsentBoundaries(); const issues=[...stages.missing.map(s=>({type:"missing_module",message:s.notes,stage:s.id})),...links.issues.map(i=>({type:"missing_link",message:i.label,page:i.page})),...storage.invalid.map(k=>({type:"invalid_storage",message:k.key}))]; const score=Math.max(0,Math.min(100,Math.round((stages.available/STAGES.length)*55+(links.ok?15:5)+(consent.ok?20:0)+(storage.invalid.length?0:10)))); const status=score>=85?"strong":score>=65?"working":score>20?"partial":"empty"; const audit={generatedAt:now(options),version:VERSION,status,score,stages,dataFlow:{readOnly:["page_load","status_cards","audit_checks","graph_analysis"],mutating:["scan_sources","approve_intake","build_curation_queue","approve_curation","send_to_training","refresh_indexes"],requiresUserAction:["approve_intake","approve_curation","send_to_training","fine_tuning_export"]},links,scripts:{workbenchLoadsAudit:Boolean(global.AHAKnowledgeWorkflowAudit)},storage,consent,issues,recommendations:[],summary:"Workflow audit kontrollerer moduler, lenker, lagring, samtykkegrenser og trygg mock-flyt."}; audit.recommendations=buildWorkflowRecommendations(audit); if(options.save!==false) safe(()=>global.localStorage?.setItem(STORAGE_KEY,JSON.stringify(audit)),null); return audit;}
function loadLastAudit(){return parse(read(STORAGE_KEY))}
global.AHAKnowledgeWorkflowAudit={VERSION,STORAGE_KEY,runWorkflowAudit,checkStageAvailability,checkPageLinks,checkStorageKeys,simulateWorkflow,checkConsentBoundaries,buildWorkflowRecommendations,loadLastAudit}; if(typeof module!=="undefined"&&module.exports)module.exports=global.AHAKnowledgeWorkflowAudit;
})(typeof window!=="undefined"?window:globalThis);
