// AHA Knowledge Curation V1 – rydder, grupperer og prioriterer Data Intake før varig kunnskap.
(function(global){"use strict";
const STORAGE_KEY="aha_knowledge_curation_v1"; const TYPE="knowledge_curation_item";
const STATUSES=["new","review","approved","merged","dismissed","exported"];
const TARGETS=["training_corpus","meta_insights_memory","personal_retrieval","training_examples","history_go_discovery","aha_music_canon"];
const ACTIONS=["approve_to_training","merge_duplicates","create_memory_claim","create_project_note","create_concept_explanation","send_to_history_go","send_to_music_canon","dismiss"];
function pipelineBoundaryMeta(extra = {}) { return { source_app: "aha", origin_app: extra.origin_app || "aha_knowledge_pipeline", local_only: true, manual_review_required: true, candidate_only: extra.candidate_only ?? false, approval_required: true, auto_training_enabled: false, fine_tuning_enabled: false, backend_enabled: false, echonet_shared: false, sync_enabled: false, historygo_writeback_enabled: false, writes_to_insight_chamber: false, canonical_engine: false, ...extra }; }
function isUnavailableRecord(record) { return Boolean(record?.deleted_at || record?.deletedAt || record?.archived === true || record?.status === "archived" || record?.status === "dismissed"); }
function storage(){try{return global.localStorage||null;}catch{return null;}} function parse(r,f){try{const v=JSON.parse(r);return v??f;}catch{return f;}}
function arr(v){return Array.isArray(v)?v:(typeof v==="string"?v.split(","):[]);} function obj(v){return v&&typeof v==="object"&&!Array.isArray(v)?v:{}} function text(v){return String(v??"").trim();}
function uniq(v){const seen=new Set();return arr(v).map(x=>text(x?.label||x?.name||x)).filter(Boolean).filter(x=>{const k=x.toLowerCase(); if(seen.has(k))return false; seen.add(k); return true;});}
function now(){return new Date().toISOString();} function id(p="curation"){return `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;}
function hash(v){const s=text(v).replace(/\s+/g," ").toLowerCase();let h=5381;for(let i=0;i<s.length;i++)h=((h<<5)+h+s.charCodeAt(i))>>>0;return `t${h.toString(36)}_${s.length}`;}
function tokens(v){return text(v).toLowerCase().replace(/[^a-z0-9æøå\s-]/gi," ").split(/\s+/).filter(t=>t.length>2);} function overlap(a,b){const A=new Set(tokens(a)),B=new Set(tokens(b)); if(!A.size||!B.size)return 0; let n=0; A.forEach(t=>{if(B.has(t))n++;}); return n/Math.max(A.size,B.size);} function addUnique(a,b){return uniq([...(a||[]),...(b||[])]);} function hasContent(i){return Boolean(text(i.text||i.summary||i.title)||Object.keys(obj(i.meta)).length);} function sourceText(i){return text(i.text||i.summary||i.excerpt||i.title);} function sourceId(i){return text(i.sourceId||i.source_id||i.id);} function lowerHay(items){return arr(items).map(i=>`${i.title} ${i.summary} ${i.text} ${arr(i.tags).join(" ")} ${arr(i.concepts).join(" ")} ${arr(i.entities).join(" ")}`).join(" ").toLowerCase();}
function normalizeCurationItem(input){const s=obj(input), created=s.createdAt||s.created_at||now(); const existingMeta=obj(s.meta); const status=STATUSES.includes(text(s.status))?text(s.status):"review"; return {id:text(s.id)||id(),type:TYPE,local_only:true,curation_only:true,manual_review_required:true,approval_required:true,auto_export_enabled:false,auto_training_enabled:false,fine_tuning_enabled:false,backend_enabled:false,echonet_shared:false,sync_enabled:false,historygo_writeback_enabled:false,writes_to_insight_chamber:false,canonical_engine:false,title:text(s.title)||"Uten tittel",summary:text(s.summary),status,sourceItemIds:uniq(s.sourceItemIds||s.source_item_ids),sources:uniq(s.sources),sourceTypes:uniq(s.sourceTypes||s.source_types),theme:text(s.theme),project:text(s.project),concepts:uniq(s.concepts),entities:uniq(s.entities),tags:uniq(s.tags),clusterKey:text(s.clusterKey||s.cluster_key)||hash(`${s.project||""}:${arr(s.concepts).join(":")}:${s.title||""}`),confidence:Number.isFinite(Number(s.confidence))?Number(s.confidence):0.55,suggestedTargets:uniq(s.suggestedTargets||s.suggested_targets).filter(t=>TARGETS.includes(t)),recommendedAction:ACTIONS.includes(text(s.recommendedAction||s.recommended_action))?text(s.recommendedAction||s.recommended_action):"approve_to_training",priority:["high","medium","low"].includes(text(s.priority))?text(s.priority):"medium",createdAt:created,updatedAt:s.updatedAt||s.updated_at||created,approvedAt:s.approvedAt||"",dismissedAt:s.dismissedAt||"",meta:{...existingMeta,...pipelineBoundaryMeta({origin_app:"aha_knowledge_curation",object_type:"knowledge_curation_item",curation_only:true})}};}
function loadAllCurationItems(){return arr(parse(storage()?.getItem(STORAGE_KEY)||"[]",[])).map(normalizeCurationItem);} function loadCurationItems(){return loadAllCurationItems().filter(i=>!["dismissed"].includes(i.status));} function saveCurationItems(items){const out=arr(items).map(normalizeCurationItem);try{storage()?.setItem(STORAGE_KEY,JSON.stringify(out));}catch{}return out;}
function clusterIntakeItems(items){const clusters=[]; arr(items).forEach(item=>{const project=text(item.project), concepts=uniq(item.concepts), tags=uniq(item.tags), entities=uniq(item.entities); const base=[project||"no_project",...(concepts.length?concepts:tags).slice(0,2),item.source,item.sourceType].filter(Boolean).join(":").toLowerCase(); let c=clusters.find(x=> (project&&x.project===project) || concepts.some(k=>x.concepts.map(v=>v.toLowerCase()).includes(k.toLowerCase())) || overlap(x.title+" "+x.items.map(sourceText).join(" "), item.title+" "+sourceText(item))>0.42); if(!c){c={clusterKey:hash(base||item.title||sourceText(item)),title:item.title||project||concepts[0]||"Kurateringsgruppe",items:[],theme:concepts[0]||tags[0]||project||item.sourceType,project,concepts:[],score:0};clusters.push(c);} c.items.push(item); c.concepts=addUnique(c.concepts,concepts); if(!c.project&&project)c.project=project; c.score=Math.min(1,0.35+c.items.length*0.15+c.concepts.length*0.08+tags.length*0.03+entities.length*0.03);}); return clusters;}
function detectDuplicates(items){const groups=[]; const push=(key,item)=>{if(!key)return; let g=groups.find(x=>x.key===key); if(!g){g={key,items:[]}; groups.push(g);} if(!g.items.some(i=>i.id===item.id))g.items.push(item);}; arr(items).forEach(i=>{if(i.source&&sourceId(i))push(`source:${i.source}:${sourceId(i)}`,i); const st=sourceText(i); if(st)push(`hash:${hash(st)}`,i); [i.meta?.chatMessageId,i.meta?.evaluationId,i.meta?.corpusId,i.chatMessageId,i.evaluationId,i.corpusId].filter(Boolean).forEach(v=>push(`linked:${v}`,i));}); arr(items).forEach((a,ix)=>arr(items).slice(ix+1).forEach(b=>{if(overlap((a.title||"")+" "+sourceText(a),(b.title||"")+" "+sourceText(b))>0.82)push(`similar:${hash(a.title||sourceText(a))}`,a),push(`similar:${hash(a.title||sourceText(a))}`,b);})); const duplicateGroups=groups.filter(g=>g.items.length>1).map(g=>({key:g.key,items:g.items,ids:g.items.map(i=>i.id),count:g.items.length})); return {duplicateGroups,duplicateCount:duplicateGroups.reduce((n,g)=>n+g.count,0)};}
function buildThemeSummary(cluster){const c=obj(cluster), concepts=uniq(c.concepts).slice(0,4), p=text(c.project); return `Dette handler om ${p||c.theme||c.title||"AHA-kunnskap"}${concepts.length?`, særlig ${concepts.join(", ")}`:""}. Materialet er samlet fra ${arr(c.items).length} kilde${arr(c.items).length===1?"":"r"} før godkjenning til varig kunnskap.`;}
function suggestTargetsForCluster(cluster){const items=arr(cluster.items); const hay=lowerHay(items); const out=[]; const add=t=>{if(!out.includes(t))out.push(t);}; if(hay.length>120||cluster.project) add("training_corpus"); if(/\b(jeg|meg|min|mine|selvinnsikt|foretrekker|ønsker|jobber med|confirmed|bekreftet)\b/.test(hay)) add("meta_insights_memory"); if(arr(cluster.concepts).length||/begrep|forklar|konsept|hvordan|hva er/.test(hay)) add("training_examples"); if(/sted|place|by|museum|histor|artist|person/.test(hay)||items.some(i=>i.source==="history_go")) add("history_go_discovery"); if(/sang|artist|album|playlist|spotify|musikk|track/.test(hay)||items.some(i=>i.source==="aha_music")) add("aha_music_canon"); if(items.some(i=>i.status==="approved"&&i.consent?.useForRetrieval)) add("personal_retrieval"); return out.length?out:["training_corpus"];}
function actionForTargets(targets, dup){ if(dup)return "merge_duplicates"; if(targets.includes("meta_insights_memory"))return "create_memory_claim"; if(targets.includes("training_examples"))return "create_concept_explanation"; if(targets.includes("history_go_discovery"))return "send_to_history_go"; if(targets.includes("aha_music_canon"))return "send_to_music_canon"; return "approve_to_training";}
function buildCurationItemsFromIntake(options={}){const api=global.AHADataIntake; const raw=api?.loadQueue?.()||[]; const eligible=raw.filter(i=>["new","review","approved"].includes(i.status)&&hasContent(i)&&!isUnavailableRecord(i)); const existing=loadAllCurationItems(); const used=new Set(existing.flatMap(i=>i.sourceItemIds)); const fresh=eligible.filter(i=>!used.has(i.id)); const clusters=clusterIntakeItems(fresh); const dup=detectDuplicates(fresh); const created=clusters.map(c=>{const targets=suggestTargetsForCluster(c); return normalizeCurationItem({title:c.title,summary:buildThemeSummary(c),status:"review",sourceItemIds:c.items.map(i=>i.id),sources:uniq(c.items.map(i=>i.source)),sourceTypes:uniq(c.items.map(i=>i.sourceType)),theme:c.theme,project:c.project,concepts:c.concepts,entities:uniq(c.items.flatMap(i=>i.entities)),tags:uniq(c.items.flatMap(i=>i.tags)),clusterKey:c.clusterKey,confidence:c.score,suggestedTargets:targets,recommendedAction:actionForTargets(targets, dup.duplicateGroups.some(g=>g.items.some(i=>c.items.includes(i)))),meta:{source:"data_intake",sourceItems:c.items.map(i=>({id:i.id,title:i.title,text:i.text||i.summary,consent:i.consent}))}});}); const all=prioritizeCurationItems([...created,...existing]); if(!options.dryRun)saveCurationItems(all); return {ok:true,created:created.length,skipped:eligible.length-fresh.length,total:all.length,items:created};}
function prioritizeCurationItems(items){const counts={}; arr(items).forEach(i=>{counts[i.theme]=(counts[i.theme]||0)+1;}); return arr(items).map(i=>normalizeCurationItem({...i,priority:(i.sourceItemIds.length>=3||counts[i.theme]>1||/personal ai|aha|training|confirmed|bekreftet/i.test(i.theme+i.summary))?"high":(i.suggestedTargets.length&&i.summary.length>40?"medium":"low"),updatedAt:now()}));}
function update(id,patch){const all=loadAllCurationItems(); const ix=all.findIndex(i=>i.id===id); if(ix<0)return null; all[ix]=normalizeCurationItem({...all[ix],...patch,id:all[ix].id,createdAt:all[ix].createdAt,updatedAt:now()}); saveCurationItems(all); return all[ix];} function approveCurationItem(itemId){const item=findItem(itemId); return update(itemId,{status:"approved",approvedAt:now(),meta:{...obj(item?.meta),approval:pipelineBoundaryMeta({origin_app:"aha_knowledge_curation",object_type:"curation_approval",curation_only:true,approved_locally:true})}});} function dismissCurationItem(itemId,reason){return update(itemId,{status:"dismissed",dismissedAt:now(),meta:{...(loadAllCurationItems().find(i=>i.id===itemId)?.meta||{}),dismissReason:reason}});}
function mergeCurationItems(ids,options={}){const all=loadAllCurationItems(); const set=new Set(arr(ids)); const chosen=all.filter(i=>set.has(i.id)); if(chosen.length<2)return null; const merged=normalizeCurationItem({title:options.title||chosen[0].title,summary:options.summary||chosen.map(i=>i.summary).filter(Boolean).join("\n"),status:"review",sourceItemIds:uniq(chosen.flatMap(i=>i.sourceItemIds)),sources:uniq(chosen.flatMap(i=>i.sources)),sourceTypes:uniq(chosen.flatMap(i=>i.sourceTypes)),theme:options.theme||chosen[0].theme,project:options.project||chosen.find(i=>i.project)?.project||"",concepts:uniq(chosen.flatMap(i=>i.concepts)),entities:uniq(chosen.flatMap(i=>i.entities)),tags:uniq(chosen.flatMap(i=>i.tags)),suggestedTargets:uniq(chosen.flatMap(i=>i.suggestedTargets)),recommendedAction:"approve_to_training",priority:"high",meta:{mergedFrom:chosen.map(i=>i.id),...chosen.reduce((m,i)=>Object.assign(m,obj(i.meta)),{})}}); saveCurationItems([merged,...all.filter(i=>!set.has(i.id)).map(i=>set.has(i.id)?{...i,status:"merged"}:i)]); return merged;}
function findItem(id){return loadAllCurationItems().find(i=>i.id===id);} function collectSourceText(item){return [item.summary,...arr(item.meta?.sourceItems).map(i=>i.text||i.summary)].filter(Boolean).join("\n\n");}
function sendToTrainingCorpus(itemId,options={}){const item=findItem(itemId), api=global.AHATrainingCorpus; if(!item)return {ok:false,error:"missing_item"}; if(item.status!=="approved"&&!options.force)return {ok:false,error:"needs_approval"}; if(!api?.addCorpusItem)return {ok:false,error:"missing_training_corpus"}; const added=api.addCorpusItem({source:"knowledge_curation",sourceId:item.id,sourceType:"manual_text",title:item.title,text:collectSourceText(item),summary:item.summary,project:item.project,tags:item.tags,concepts:item.concepts,status:"raw",consent:{useForMemory:true,useForTrainingExamples:true,useForFineTuning:false,useForStyle:false,useForKnowledge:true},meta:{curationItemId:item.id,sourceItemIds:item.sourceItemIds,...pipelineBoundaryMeta({origin_app:"aha_knowledge_curation",object_type:"training_corpus_export",curation_only:true})}}); if(added)update(item.id,{status:"exported",meta:{...item.meta,trainingCorpusId:added.id}}); return {ok:Boolean(added),item:added};}
function sendToMetaInsightsMemory(itemId){const item=findItem(itemId); if(!item)return {ok:false,error:"missing_item"}; return {ok:true,planned:true,local_only:true,suggestion_only:true,writes_to_insight_chamber:false,candidate:{id:id("memory_candidate"),status:"needs_confirmation",claimText:item.summary,title:item.title,source:"knowledge_curation",curationItemId:item.id,meta:pipelineBoundaryMeta({origin_app:"aha_knowledge_curation",object_type:"memory_candidate",curation_only:true})}};}
function sendToTrainingExamples(itemId){const item=findItem(itemId), api=global.AHATrainingExamples; if(!item)return {ok:false,error:"missing_item"}; if(!api?.addExample)return {ok:false,error:"missing_training_examples"}; const ex=api.addExample({source:"knowledge_curation",taskType:"concept_explanation",input:item.title,output:item.summary,language:"no",status:"needs_review",labels:item.concepts,meta:{curationItemId:item.id,...pipelineBoundaryMeta({origin_app:"aha_knowledge_curation",object_type:"training_example_export",curation_only:true})}}); return {ok:Boolean(ex),item:ex};}
function collectCurationStats(){const all=loadAllCurationItems(); const s={total:all.length,new:0,review:0,approved:0,merged:0,dismissed:0,exported:0,byTheme:{},byProject:{},byTarget:{},highPriority:0,duplicateGroups:detectDuplicates(all).duplicateGroups.length,trainingReady:0,memoryReady:0,historyGoReady:0,musicCanonReady:0}; all.forEach(i=>{s[i.status]=(s[i.status]||0)+1; if(i.theme)s.byTheme[i.theme]=(s.byTheme[i.theme]||0)+1; if(i.project)s.byProject[i.project]=(s.byProject[i.project]||0)+1; i.suggestedTargets.forEach(t=>s.byTarget[t]=(s.byTarget[t]||0)+1); if(i.priority==="high")s.highPriority++; if(i.status==="approved"&&i.suggestedTargets.includes("training_corpus"))s.trainingReady++; if(i.suggestedTargets.includes("meta_insights_memory"))s.memoryReady++; if(i.suggestedTargets.includes("history_go_discovery"))s.historyGoReady++; if(i.suggestedTargets.includes("aha_music_canon"))s.musicCanonReady++;}); return s;}
function buildCurationSummary(){const s=collectCurationStats(); const topThemes=Object.entries(s.byTheme).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([theme,count])=>({theme,count})); const nextAction=s.highPriority?"Godkjenn high-priority curation items.":s.duplicateGroups?"Slå sammen duplikater før Training Corpus.":s.trainingReady?"Send kuratert kunnskap til Training.":"Bygg kurateringskø fra Data Intake."; return {available:true,total:s.total,reviewCount:s.new+s.review,highPriority:s.highPriority,duplicateGroups:s.duplicateGroups,trainingReady:s.trainingReady,topThemes,nextAction};}
global.AHAKnowledgeCuration={STORAGE_KEY,TYPE,TARGETS,ACTIONS,pipelineBoundaryMeta,isUnavailableRecord,loadCurationItems,loadAllCurationItems,saveCurationItems,normalizeCurationItem,buildCurationItemsFromIntake,clusterIntakeItems,detectDuplicates,buildThemeSummary,suggestTargetsForCluster,prioritizeCurationItems,approveCurationItem,dismissCurationItem,mergeCurationItems,sendToTrainingCorpus,sendToMetaInsightsMemory,sendToTrainingExamples,collectCurationStats,buildCurationSummary};
if(typeof module!=="undefined"&&module.exports)module.exports=global.AHAKnowledgeCuration;
})(typeof window!=="undefined"?window:globalThis);
