// AHA Local Insight Home Dashboard V1
(function (global) {
  "use strict";
  const $ = (id) => global.document?.getElementById(id);
  const esc = (v) => String(v == null ? "" : v).replace(/[&<>"']/g, (c) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[c]));
  function list(items, render) { return (Array.isArray(items) && items.length ? items : []).map(render).join(""); }
  function set(id, html) { const node = $(id); if (node) node.innerHTML = html; }
  function renderHero(payload) { set("aha-local-home-hero", `<p class="eyebrow">AHA Local Insight Home</p><h2>${esc(payload.headline)}</h2><p>${esc(payload.summary)}</p><div class="aha-tile-actions"><a class="aha-tile-btn aha-tile-btn-primary" href="knowledge-workbench.html">Åpne Knowledge Workbench</a><a class="aha-tile-btn" href="chat.html">Åpne Chat</a></div>`); }
  function renderNextAction(payload) { const a = payload.nextActions?.[0] || {}; set("aha-local-home-next-action", `<p class="eyebrow">Neste handling</p><h3>${esc(a.label || "Åpne Chat")}</h3><p>${esc(a.description || "Fortsett i AHA Chat.")}</p><a class="aha-tile-btn aha-tile-btn-primary" href="${esc(a.href || "chat.html")}">${esc(a.label || "Åpne Chat")}</a>`); }
  function renderHighlights(payload) { set("aha-local-home-highlights", `<p class="eyebrow">Innsikt akkurat nå</p><h3>Nye signaler</h3><div class="aha-local-card-grid">${list(payload.highlights, (h) => `<article class="aha-local-card"><strong>${esc(h.title)}</strong><p>${esc(h.summary)}</p><small>${esc(h.source)} · ${esc(h.severity)}</small><a href="${esc(h.href)}">${esc(h.actionLabel || "Åpne")}</a></article>`)}</div>`); }
  function renderActiveWork(payload) { set("aha-local-home-active-work", `<p class="eyebrow">Aktivt kunnskapsarbeid</p><h3>Kø og status</h3><div class="aha-profile-status-grid">${list(payload.pendingWork, (w) => `<a class="aha-mini-stat" href="${esc(w.href)}"><strong>${esc(w.count || w.status || 0)}</strong><span>${esc(w.label)}</span></a>`)}</div>`); }
  function renderProjectsConcepts(payload) { const c = payload.counts || {}; set("aha-local-home-projects", `<p class="eyebrow">Prosjekter og begreper</p><h3>Kunnskapskart</h3><div class="aha-profile-status-grid"><div class="aha-mini-stat"><strong>${esc(c.activeProjects || 0)}</strong><span>aktive prosjekter</span></div><div class="aha-mini-stat"><strong>${esc(c.topConcepts || 0)}</strong><span>begreper</span></div><div class="aha-mini-stat"><strong>${esc(c.mapNodes || 0)}</strong><span>nodes</span></div><div class="aha-mini-stat"><strong>${esc(c.mapEdges || 0)}</strong><span>edges</span></div></div><ul class="aha-activity-list">${list(payload.activeProjects, (p) => `<li><strong>${esc(p.title)}</strong><span>${esc(p.count || p.score || 0)}</span></li>`)}</ul>`); }
  function renderRecentActivity(payload) { set("aha-local-home-recent", `<p class="eyebrow">Siste aktivitet</p><h3>Lokale spor</h3><ul class="aha-activity-list">${list(payload.recentActivity, (a) => `<li><a href="${esc(a.href)}"><strong>${esc(a.label)}</strong><span>${esc(a.title)}</span><small>${esc(a.timestamp)}</small></a></li>`) || `<li><span>Ingen tidsstemplet aktivitet ennå.</span></li>`}</ul>`); }
  function renderModuleTiles(payload) { set("aha-local-home-module-tiles", `<p class="eyebrow">Moduler</p><h3>Faktisk lokalt innhold</h3><div class="aha-local-module-grid">${list(payload.moduleTiles, (t) => `<a class="aha-local-module-tile" href="${esc(t.href)}"><strong>${esc(t.title)}</strong><small>${esc(t.status)}</small>${list(t.metrics, (m) => `<span>${esc(m)}</span>`)}</a>`)}</div>`); }
  function render(payload) { if (!payload) return; renderHero(payload); renderNextAction(payload); renderHighlights(payload); renderActiveWork(payload); renderProjectsConcepts(payload); renderRecentActivity(payload); renderModuleTiles(payload); bindActions(); }
  function bindActions() { const btn = $("aha-local-home-refresh"); if (btn && !btn.dataset.bound) { btn.dataset.bound = "true"; btn.addEventListener("click", () => render(global.AHALocalInsightHome?.refreshHome?.({ save: true }))); } }
  function init() { const payload = global.AHALocalInsightHome?.refreshHome?.({ save: true }); render(payload); }
  global.AHALocalInsightHomeDashboard = { init, render, renderHero, renderNextAction, renderHighlights, renderActiveWork, renderProjectsConcepts, renderRecentActivity, renderModuleTiles, bindActions };
  if (global.document) global.document.addEventListener("DOMContentLoaded", init);
})(typeof window !== "undefined" ? window : globalThis);
