// AHA Personal Answer Evaluation V1 – evaluerer AHA-svar mot personlig svargrunnlag.
(function (global) {
  "use strict";
  const VERSION = "v1";
  const STORAGE_KEY = "aha_personal_answer_evaluations_v1";
  const CRITERIA = { intentAlignment: true, sourceGrounding: true, personalRelevance: true, nextStepClarity: true, transparency: true, brevity: true };
  const WEIGHTS = { intentAlignment: 20, sourceGrounding: 25, personalRelevance: 20, transparency: 15, nextStep: 15, brevity: 5 };
  function asArray(v){ return Array.isArray(v) ? v : []; }
  function asObject(v){ return v && typeof v === "object" && !Array.isArray(v) ? v : {}; }
  function asText(v){ return String(v ?? "").trim(); }
  function oneLine(v){ return asText(v).replace(/\s+/g," "); }
  function norm(v){ return oneLine(v).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,""); }
  function now(options={}){ return new Date(options.now || Date.now()).toISOString(); }
  function clamp(n,max=100){ return Math.max(0, Math.min(max, Math.round(Number(n)||0))); }
  function unique(items){ return [...new Set(asArray(items).map(oneLine).filter(Boolean))]; }
  function words(text){ return norm(text).split(/[^a-z0-9æøå]+/i).filter((w)=>w.length>3); }
  function statusFromScore(score){ if (score <= 0) return "empty"; if (score < 30) return "weak"; if (score < 60) return "usable"; if (score < 80) return "good"; return "strong"; }
  function label(score){ return score >= 80 ? "strong" : score >= 60 ? "good" : score >= 30 ? "usable" : "weak"; }
  function getContext(pack){ return asObject(pack?.context || pack); }
  function getSources(pack){ return asArray(getContext(pack).selectedSources || pack?.selectedSources).map((s,i)=>({
    source: asText(s.source), sourceId: asText(s.sourceId || s.id), sourceType: asText(s.sourceType), title: oneLine(s.title || s.excerpt || `Kilde ${i+1}`), excerpt: oneLine(s.excerpt || s.text || ""), lexicalScore: Number(s.lexicalScore ?? s.score)||0, semanticScore: Number(s.semanticScore)||0, hybridScore: Number(s.hybridScore ?? s.score)||0, reasons: unique(s.reasons).slice(0,8), project: oneLine(s.project), concepts: unique(s.concepts), taskType: asText(s.taskType), id: asText(s.id || s.sourceId || `eval-source-${i+1}`)
  })); }
  function buildEvaluationInput(userMessage, answerText, answerPackage, options={}){
    const ctx = getContext(answerPackage); const st = asObject(answerPackage?.status);
    return { generatedAt: now(options), version: VERSION, userMessage: oneLine(userMessage), answerText: oneLine(answerText), answerPackage: answerPackage || null, selectedSources: getSources(answerPackage), answerIntent: asText(ctx.answerIntent || st.intent || options.answerIntent || "unknown"), answerPlan: asObject(ctx.answerPlan || options.answerPlan), retrievalMode: asText(ctx.retrieval?.mode || (st.hasSemanticRetrieval ? "hybrid" : st.hasRetrieval ? "lexical" : "none")), personalContextStatus: asObject(ctx.personalContext?.status || ctx.personalContext?.context?.readiness || { available: Boolean(ctx.personalContext) }), evaluationCriteria: { ...CRITERIA } };
  }
  function evaluateIntentAlignment(userMessage, answerText, answerIntent, answerPlan){
    const t = norm(answerText), intent = asText(answerIntent)||"unknown"; if (!t) return { score:0, label:"empty", reason:"Svaret er tomt." };
    let score = /\b(status|ståa|fremdrift|framdrift)\b/.test(t) ? 55 : 45;
    if (intent === "project_status") score = (/\b(status|ståa|nå|ferdig|gjenstår)\b/.test(t)?55:25) + (/\b(neste steg|videre|nå bør|start med)\b/.test(t)?35:0);
    else if (intent === "planning") score = (/\b(plan|steg|1\.|først|deretter|prioriter)\b/.test(t)?70:35) + (/\b(neste steg|kontrollpunkt|frist)\b/.test(t)?20:0);
    else if (intent === "technical_help") score = (/\b(kode|test|fil|implementer|feil|kommando|pr)\b/.test(t)?75:35) + (/\b(neste steg|kjør|endre|sjekk)\b/.test(t)?15:0);
    else if (intent === "training_model") score = (/\b(corpus|rag|retrieval|fine.?tuning|modelltilpasning|training example)\b/.test(t)?85:35);
    else if (intent === "meta_insight") score = (/\b(selvinnsikt|mønster|hypotese|tolkning|forsiktig|bekreftet)\b/.test(t)?85:35);
    else if (asArray(answerPlan?.sections).some((s)=>t.includes(norm(s)))) score += 15;
    return { score: clamp(score), label: label(score), reason: `${intent}-intensjon vurdert mot svartekst og svarplan.` };
  }
  function sourceTerms(s){ return unique([s.title, s.project, ...asArray(s.concepts), ...words(s.excerpt).slice(0,12)]); }
  function evaluateSourceGrounding(answerText, selectedSources){
    const text = norm(answerText); const sources = asArray(selectedSources); if (!text) return { score:0, usedSources:[], unusedSources:sources, matchedTerms:[], reason:"Tomt svar." };
    if (!sources.length) return { score:45, usedSources:[], unusedSources:[], matchedTerms:[], reason:"Nyttig svar kan finnes, men ingen valgte kilder var tilgjengelige." };
    const matchedTerms=[]; const used=[]; const unused=[];
    sources.forEach((s)=>{ const terms = sourceTerms(s).filter((term)=>term && norm(term).length>3 && text.includes(norm(term))); if (terms.length){ matchedTerms.push(...terms.slice(0,6)); used.push({ ...s, used:true, matchedTerms:terms.slice(0,6), sourceUseLabel:"kilde brukt" }); } else unused.push({ ...s, used:false, sourceUseLabel:"kilde valgt, men lite brukt" }); });
    const ratio = used.length / sources.length; let score = ratio * 70 + Math.min(20, unique(matchedTerms).length*3);
    used.forEach((s)=>{ if (/confirmed|important/.test(s.sourceType) || asArray(s.reasons).some((r)=>/bekreftet|confirmed/i.test(r))) score += 8; if ((Number(s.hybridScore)||0) >= .7) score += 5; });
    return { score: clamp(score || (text.length>40 ? 35 : 15)), usedSources: used, unusedSources: unused, matchedTerms: unique(matchedTerms).slice(0,20), reason: `${used.length} av ${sources.length} valgte kilder er synlige i svaret.` };
  }
  function evaluatePersonalRelevance(answerText, answerPackage){
    const text = norm(answerText), ctx = getContext(answerPackage); const signals=[]; getSources(answerPackage).forEach((s)=>{ [s.project,...asArray(s.concepts),s.title].forEach((x)=>{ if (x && text.includes(norm(x))) signals.push(x); }); });
    asArray(ctx.personalContext?.context?.projects).forEach((p)=>{ const v=p?.label||p; if (v && text.includes(norm(v))) signals.push(v); });
    asArray(ctx.personalContext?.context?.activeSelfModel?.confirmedClaims).forEach((c)=>{ const v=c?.claimText||c?.text||c; words(v).slice(0,4).forEach((w)=>{ if (text.includes(w)) signals.push(w); }); });
    if (/\b(personlig grunnlag|selvinnsikt|dine prosjekter|godkjent materiale|aha vet)\b/.test(text)) signals.push("personlig grunnlag");
    const score = clamp(25 + unique(signals).length*15, 100); return { score: text?score:0, label: label(score), reason: unique(signals).length ? "Svaret bruker personlige signaler." : "Få tydelige personlige signaler i svaret.", matchedPersonalSignals: unique(signals).slice(0,12) };
  }
  function evaluateTransparency(answerText, answerPackage){ const t=norm(answerText); if(!t) return {score:0,label:"empty",reason:"Tomt svar."}; let s=20; if(/personlig grunnlag|godkjent materiale|kilde|kilder|basert på|jeg ser/.test(t)) s+=35; if(/status|vurdering|neste steg|grunnlag/.test(t)) s+=25; if(getSources(answerPackage).length && /kilde|grunnlag|reasons|funn/.test(t)) s+=20; return {score:clamp(s), label:label(s), reason:"Vurderer om grunnlag, vurdering og neste steg er forklarbart."}; }
  function evaluateNextStep(answerText, answerPlan){ const t=norm(answerText); const found=/\b(neste steg|nå bør|start med|gjør dette|prioriter|1\.|først|deretter|kontrollpunkt)\b/.test(t); const planHint=asText(answerPlan?.suggestedFollowup); const score=found ? (planHint && t.includes(norm(planHint).slice(0,12)) ? 95 : 80) : 25; return { score, nextStepFound: found, reason: found ? "Svaret har et tydelig neste steg." : "Svaret mangler et tydelig neste steg." }; }
  function brevityScore(text){ const n=words(text).length; return !n ? 0 : n <= 180 ? 100 : n <= 320 ? 75 : 45; }
  function buildImprovementSuggestions(e){ const d=asObject(e.dimensions); const out=[]; if((d.sourceGrounding?.score||0)<65) out.push("Bruk flere av de valgte kildene i svaret."); if((d.nextStep?.score||0)<70) out.push("Gjør neste steg mer konkret."); if((d.transparency?.score||0)<70) out.push("Forklar hvorfor kilden er relevant."); if((d.personalRelevance?.score||0)<70) out.push("Knytt svaret tydeligere til brukerens aktive prosjekt."); if((d.intentAlignment?.score||0)<70) out.push("Svar mer direkte på brukerens intensjon."); if(!out.length) out.push("Bruk et godkjent training example som mønster.", "Bevar den tydelige koblingen mellom kilder og neste steg."); return out.slice(0,5); }
  function taskTypeFor(intent){ return intent==="project_status"||intent==="planning"?"project_explanation":intent==="training_model"?"concept_explanation":intent==="meta_insight"?"memory_fact":"question_answer"; }
  function buildTrainingSuggestion(userMessage, answerText, evaluation, answerPackage){ const intent=asText(evaluation?.evidence?.answerIntent || getContext(answerPackage).answerIntent); const ok=(evaluation?.score||0)>=70 && asText(answerText).length>40; const tt=taskTypeFor(intent); return { shouldCreateExample: ok, suggestedTaskType: tt, reason: ok ? "Svaret er godt nok til å foreslås som needs_review training example." : "Svaret bør forbedres før det blir treningseksempel.", draftExample: { taskType: tt, input: oneLine(userMessage), output: oneLine(answerText), language: /[æøå]/i.test(`${userMessage} ${answerText}`)?"no":"unknown", status:"needs_review", meta:{ source:"aha_personal_answer_evaluation", evaluationScore:evaluation?.score||0, evaluationStatus:evaluation?.status||"unknown", intent, createdAt:now() } } }; }
  function evaluateAnswer(userMessage, answerText, answerPackage, options={}){ const input=buildEvaluationInput(userMessage, answerText, answerPackage, options); if(!input.answerText) return { generatedAt:input.generatedAt, version:VERSION, status:"empty", score:0, dimensions:{}, sourceUse:{score:0,usedSources:[],unusedSources:input.selectedSources,matchedTerms:[],reason:"Tomt svar."}, intentAlignment:{score:0,label:"empty",reason:"Tomt svar."}, personalRelevance:{score:0,label:"empty",reason:"Tomt svar.",matchedPersonalSignals:[]}, transparency:{score:0,label:"empty",reason:"Tomt svar."}, nextStep:{score:0,nextStepFound:false,reason:"Tomt svar."}, improvementSuggestions:["Skriv et svar før evaluering."], trainingSuggestion:{shouldCreateExample:false,suggestedTaskType:"question_answer",reason:"Tomt svar.",draftExample:null}, summary:"Tomt svar kan ikke evalueres.", evidence:{...input} };
    const intent=evaluateIntentAlignment(input.userMessage,input.answerText,input.answerIntent,input.answerPlan), sourceUse=evaluateSourceGrounding(input.answerText,input.selectedSources), personal=evaluatePersonalRelevance(input.answerText,input.answerPackage), transparency=evaluateTransparency(input.answerText,input.answerPackage), nextStep=evaluateNextStep(input.answerText,input.answerPlan), brevity={score:brevityScore(input.answerText),label:label(brevityScore(input.answerText)),reason:"Vurderer korthet og nytte."};
    const dimensions={ intentAlignment:intent, sourceGrounding:sourceUse, personalRelevance:personal, transparency, nextStep, brevity }; const score=clamp(intent.score*.20 + sourceUse.score*.25 + personal.score*.20 + transparency.score*.15 + nextStep.score*.15 + brevity.score*.05); const evaluation={ generatedAt:input.generatedAt, version:VERSION, status:statusFromScore(score), score, dimensions, sourceUse, intentAlignment:intent, personalRelevance:personal, transparency, nextStep, improvementSuggestions:[], trainingSuggestion:null, summary:`Svar-evaluering: ${score}/100 (${statusFromScore(score)}).`, evidence:{ answerIntent:input.answerIntent, retrievalMode:input.retrievalMode, selectedSources:input.selectedSources, personalContextStatus:input.personalContextStatus } }; evaluation.improvementSuggestions=buildImprovementSuggestions(evaluation); evaluation.trainingSuggestion=buildTrainingSuggestion(input.userMessage,input.answerText,evaluation,input.answerPackage); return evaluation; }
  function loadEvaluations(){ try{return asArray(JSON.parse(global.localStorage?.getItem(STORAGE_KEY)||"[]")).filter((e)=>!e.deletedAt);}catch{return [];} }
  function saveEvaluation(evaluation){ const list=loadEvaluations(); const item={ id:evaluation.id||`answer_eval_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`, ...evaluation }; list.unshift(item); try{global.localStorage?.setItem(STORAGE_KEY, JSON.stringify(list.slice(0,100)));}catch{} return item; }
  function collectEvaluationStats(){ const list=loadEvaluations(); const byIntent={}; list.forEach((e)=>{ const i=e.evidence?.answerIntent||"unknown"; byIntent[i]=(byIntent[i]||0)+1; }); const avg=list.length?Math.round(list.reduce((s,e)=>s+(Number(e.score)||0),0)/list.length):0; return { total:list.length, strong:list.filter(e=>e.status==="strong").length, good:list.filter(e=>e.status==="good").length, usable:list.filter(e=>e.status==="usable").length, weak:list.filter(e=>e.status==="weak").length, averageScore:avg, byIntent, trainingSuggestions:list.filter(e=>e.trainingSuggestion?.shouldCreateExample).length, latest:list[0]||null }; }
  global.AHAPersonalAnswerEvaluation={ VERSION, STORAGE_KEY, buildEvaluationInput, evaluateAnswer, evaluateIntentAlignment, evaluateSourceGrounding, evaluatePersonalRelevance, evaluateTransparency, evaluateNextStep, buildImprovementSuggestions, buildTrainingSuggestion, saveEvaluation, loadEvaluations, collectEvaluationStats };
})(typeof window !== "undefined" ? window : globalThis);
