// AHA Personal AI Control Panel V1 – samlet status, kontroll og test for personlig AI-sløyfe.
(function (global) {
  "use strict";
  const VERSION = "v1";
  const STORAGE_KEY = "aha_personal_ai_control_status_v1";
  const DEFAULT_QUERY = "Hva vet AHA om mine viktigste prosjekter og begreper?";
  function asArray(v){ return Array.isArray(v) ? v : []; }
  function asObject(v){ return v && typeof v === "object" && !Array.isArray(v) ? v : {}; }
  function asText(v){ return String(v ?? "").trim(); }
  function now(options={}){ return new Date(options.now || Date.now()).toISOString(); }
  function safe(fn, fb){ try { return typeof fn === "function" ? fn() : fb; } catch { return fb; } }
  function num(v){ return Number(v) || 0; }
  function cap(v){ return Math.max(0, Math.min(100, Math.round(num(v)))); }
  function mod(available,label,status="empty",score=0,counts={},lastUpdated="",notes=[]){ return { available:Boolean(available), label, status, score:cap(score), counts:asObject(counts), lastUpdated:asText(lastUpdated), notes:asArray(notes).map(asText).filter(Boolean) }; }

  function memoryStatus(){ const api=global.AHAMetaInsightsMemory; const s=asObject(safe(()=>api?.summarizeMemory?.(),{})); const confirmed=asArray(s.confirmedClaims).length, important=asArray(s.importantClaims).length; return mod(Boolean(api),"Meta Insights Memory", confirmed+important?"working":"empty", Math.min(100,(confirmed+important)*20), { confirmedClaims:confirmed, importantClaims:important, total:num(s.totalFeedback)||confirmed+important }, s.updatedAt, [confirmed+important?"Bekreftet/viktig minne finnes.":"Mangler bekreftede memory claims."]); }
  function corpusStatus(){ const api=global.AHATrainingCorpus; const s=asObject(safe(()=>api?.collectCorpusStats?.(),{})); return mod(Boolean(api),"Training Corpus", num(s.approved)?"working":"empty", Math.min(100,num(s.approved)*20), s, "", [num(s.approved)?"Godkjent corpus finnes.":"Godkjenn flere corpus items."]); }
  function examplesStatus(){ const api=global.AHATrainingExamples; const s=asObject(safe(()=>api?.collectExampleStats?.(),{})); return mod(Boolean(api),"Training Examples", num(s.approved)?"working":"empty", Math.min(100,num(s.approved)*20), s, "", [num(s.approved)?"Godkjente training examples finnes.":"Lag og godkjenn training examples."]); }
  function readinessStatus(){ const api=global.AHAPersonalModelReadiness; const r=asObject(safe(()=>api?.buildReadinessReport?.(),{})); return mod(Boolean(api),"Personal Model Readiness", num(r.score)>=70?"working":num(r.score)>0?"building":"empty", num(r.score), { score:num(r.score), level:r.level, approvedCorpus:num(r.corpus?.approved), approvedExamples:num(r.examples?.approved) }, r.generatedAt, [r.summary||"Readiness ikke beregnet."]); }
  function retrievalStatus(){ const api=global.AHAPersonalRetrieval; const s=asObject(safe(()=>api?.getRetrievalStatus?.(),{})); return mod(Boolean(api),"Personal Retrieval", s.available?"working":"empty", s.available?80:0, { indexedItems:num(s.indexedItems), corpusItems:num(s.corpusItems), examples:num(s.examples), memoryClaims:num(s.memoryClaims) }, s.lastBuiltAt, [s.available?"Lexical retrieval-index er bygget.":"Bygg personlig søkeindeks."]); }
  function semanticStatus(){ const api=global.AHASemanticRetrieval; const s=asObject(safe(()=>api?.getSemanticStatus?.(),{})); return mod(Boolean(api),"Semantic Retrieval", s.available?"working":"empty", s.available?85:0, { indexedItems:num(s.indexedItems), corpusItems:num(s.corpusItems), examples:num(s.examples), memoryClaims:num(s.memoryClaims), vectorModel:s.vectorModel }, s.lastBuiltAt, [s.available?"Semantisk/hybrid indeks er bygget.":"Bygg semantisk søkeindeks."]); }
  function contextStatus(){ const api=global.AHAChatPersonalContext; const s=asObject(safe(()=>api?.getPersonalContextStatus?.(),{})); const active=Boolean(s.available)||num(s.approvedCorpus)+num(s.approvedExamples)+num(s.confirmedClaims)>0; return mod(Boolean(api),"Personal Context", active?"working":"empty", active?75:0, s, "", [active?"Chat kan bygge personlig kontekst.":"Mangler aktiv personlig kontekst."]); }
  function auditStatus(){ const api=global.AHAPersonalAiLoopAudit; const a=safe(()=>api?.loadLastAudit?.(),null); const status=asText(a?.status)||"empty"; return mod(Boolean(api),"AI Loop Audit", ["working","strong"].includes(status)?status:(a?"building":"empty"), num(a?.score), { score:num(a?.score), status, recommendations:asArray(a?.recommendations).length }, a?.generatedAt, [a?"Siste audit er tilgjengelig.":"Kjør Personal AI Loop Audit."]); }
  function composerStatus(){ const api=global.AHAPersonalAnswerComposer; const p=asObject(safe(()=>api?.buildAnswerPackage?.(DEFAULT_QUERY,{limit:3}),{})); return mod(Boolean(api),"Answer Composer", p?.status?.ready?"working":api?"building":"empty", p?.status?.ready?80:0, { selectedSourceCount:num(p?.status?.selectedSourceCount), intent:p?.status?.intent }, p?.generatedAt, [api?"Answer Composer kan bygge svargrunnlag.":"Answer Composer mangler."]); }
  function dataIntakeStatus(){ const api=global.AHADataIntake; const s=asObject(safe(()=>api?.buildIntakeSummary?.(),{})); return mod(Boolean(api),"Data Intake", num(s.reviewCount)||num(s.approvedCount)?"working":"empty", Math.min(100,(num(s.total)>0?30:0)+num(s.reviewCount)*10+num(s.approvedCount)*15+num(s.importedCount)*20), { total:num(s.total), reviewCount:num(s.reviewCount), approvedCount:num(s.approvedCount), importedCount:num(s.importedCount) }, "", [s.nextAction||"Skann AHA-kilder i Data Intake."]); }
  function evaluationStatus(){ const api=global.AHAPersonalAnswerEvaluation; const s=asObject(safe(()=>api?.collectEvaluationStats?.(),{})); return mod(Boolean(api),"Answer Evaluation", num(s.total)?"working":"building", Math.min(100, 40+num(s.averageScore)/2), s, s.latest?.generatedAt, [num(s.total)?"Lagrede evalueringer finnes.":"Test Answer Evaluation."]); }

  function collectModuleStatus(){ return { metaInsightsAgent:mod(Boolean(global.AHAMetaInsightsAgent),"Meta Insights Agent",global.AHAMetaInsightsAgent?"working":"empty",global.AHAMetaInsightsAgent?80:0), metaInsightsMemory:memoryStatus(), dataIntake:dataIntakeStatus(), trainingCorpus:corpusStatus(), trainingExamples:examplesStatus(), personalModelReadiness:readinessStatus(), chatPersonalContext:contextStatus(), personalRetrieval:retrievalStatus(), semanticRetrieval:semanticStatus(), personalAiLoopAudit:auditStatus(), personalAnswerComposer:composerStatus(), personalAnswerEvaluation:evaluationStatus() }; }
  function overallFromScore(score, m){ let status="empty", level="0_data_needed"; if(score>=85){status="strong";level="5_evaluated_loop";} else if(score>=65){status="working";level=m.personalAnswerComposer.status!="empty"?"4_answer_ready":"3_retrieval_ready";} else if(score>=35){status="building";level=m.personalRetrieval.counts.indexedItems?"3_retrieval_ready":"2_training_ready";} else if(score>=10){status="starting";level=m.metaInsightsMemory.counts.confirmedClaims||m.metaInsightsMemory.counts.importantClaims?"1_memory_ready":"0_data_needed";} return { status, score:cap(score), level, label: status==="strong"?"Sterk":status==="working"?"Fungerer":status==="building"?"Bygges":status==="starting"?"Startet":"Trenger data" }; }
  function buildRecommendations(status){ const s=status?.modules?status:buildControlStatus(); const m=s.modules; const out=[]; if(m.dataIntake.available && !m.dataIntake.counts.total) out.push("Skann AHA-kilder i Data Intake.");
    if(m.dataIntake.available && m.dataIntake.counts.reviewCount) out.push("Godkjenn nye intake items.");
    if(m.dataIntake.available && m.dataIntake.counts.approvedCount) out.push("Importer godkjent materiale til Training Corpus.");
    if(!m.trainingCorpus.counts.approved) out.push("Godkjenn flere corpus items."); if(!m.trainingExamples.counts.approved) out.push("Lag flere training examples."); if(!m.personalRetrieval.counts.indexedItems) out.push("Bygg personlig søkeindeks."); if(!m.semanticRetrieval.counts.indexedItems) out.push("Bygg semantisk søkeindeks."); if(!["working","strong"].includes(m.personalAiLoopAudit.status)) out.push("Kjør Personal AI Loop Audit."); if(!m.personalAnswerComposer.counts.selectedSourceCount) out.push("Test Answer Composer."); if(!m.personalAnswerEvaluation.counts.total) out.push("Test Answer Evaluation."); out.push("Bruk chatten med et spørsmål fra et aktivt prosjekt."); return out.slice(0,7); }
  function getNextAction(status){ const s=status?.modules?status:buildControlStatus(); const m=s.modules; if(m.dataIntake.available && (m.dataIntake.counts.reviewCount||!m.dataIntake.counts.total)) return { id:"open_data_intake", label:"Åpne Data Intake", description:"Skann AHA-kilder og godkjenn nye intake items.", href:"intake.html", action:"open_data_intake" }; if(!m.trainingCorpus.counts.approved) return { id:"open_training", label:"Åpne Training Corpus", description:"Start med å importere og godkjenne personlig materiale.", href:"training.html", action:"open_training" }; if(!m.trainingExamples.counts.approved) return { id:"open_training", label:"Lag training examples", description:"Lag og godkjenn eksempler fra corpus.", href:"training.html", action:"open_training" }; if(!m.personalRetrieval.counts.indexedItems) return { id:"build_retrieval_index", label:"Bygg personlig søkeindeks", description:"Lag lexical retrieval-index fra godkjent materiale.", href:"personal-ai.html", action:"build_retrieval_index" }; if(!m.semanticRetrieval.counts.indexedItems) return { id:"build_semantic_index", label:"Bygg semantisk søkeindeks", description:"Lag semantisk/hybrid indeks.", href:"personal-ai.html", action:"build_semantic_index" }; if(!["working","strong"].includes(m.personalAiLoopAudit.status)) return { id:"run_ai_loop_audit", label:"Kjør AI-loop audit", description:"Kontroller hele personlig AI-sløyfen.", href:"personal-ai.html", action:"run_ai_loop_audit" }; if(!m.personalAnswerEvaluation.counts.total) return { id:"test_answer_evaluation", label:"Test Answer Evaluation", description:"Evaluer et lokalt preview-svar.", href:"personal-ai.html", action:"test_answer_evaluation" }; return { id:"open_chat", label:"Åpne Chat", description:"Test Personal AI med et aktivt prosjektspørsmål.", href:"chat.html", action:"open_chat" }; }
  function buildControlStatus(options={}){ const modules=collectModuleStatus(); const score=cap((modules.metaInsightsMemory.available?10:0)+(modules.dataIntake.available?5:0)+(modules.dataIntake.counts.importedCount?5:0)+((modules.metaInsightsMemory.counts.confirmedClaims||0)+(modules.metaInsightsMemory.counts.importantClaims||0)>0?10:0)+(modules.trainingCorpus.counts.approved?10:0)+(modules.trainingExamples.counts.approved?10:0)+Math.min(15,num(modules.personalModelReadiness.counts.score)*0.15)+(modules.personalRetrieval.counts.indexedItems?10:0)+(modules.semanticRetrieval.counts.indexedItems?10:0)+(modules.chatPersonalContext.status!=="empty"?10:0)+(modules.personalAnswerComposer.available?10:0)+(modules.personalAnswerEvaluation.available?10:0)+(["working","strong"].includes(modules.personalAiLoopAudit.status)?10:0)); const overall=overallFromScore(score,modules); const status={ generatedAt:now(options), version:VERSION, overall, modules, memory:modules.metaInsightsMemory, dataIntake:modules.dataIntake, training:{ corpus:modules.trainingCorpus, examples:modules.trainingExamples }, readiness:modules.personalModelReadiness, retrieval:modules.personalRetrieval, semanticRetrieval:modules.semanticRetrieval, personalContext:modules.chatPersonalContext, aiLoopAudit:modules.personalAiLoopAudit, answerComposer:modules.personalAnswerComposer, answerEvaluation:modules.personalAnswerEvaluation, recommendations:[], nextAction:null, summary:"" }; status.recommendations=buildRecommendations(status); status.nextAction=getNextAction(status); status.summary=`Personal AI status: ${overall.label} (${overall.score}/100). Neste steg: ${status.nextAction.label}.`; return options.save===false?status:saveLastControlStatus(status); }
  function runQuickHealthCheck(options={}){ const status=buildControlStatus({...options, save:false}); const findings=[`Moduler tilgjengelig: ${Object.values(status.modules).filter(m=>m.available).length}/12.`,`Godkjent corpus: ${status.training.corpus.counts.approved||0}.`,`Godkjente examples: ${status.training.examples.counts.approved||0}.`,`Retrieval items: ${status.retrieval.counts.indexedItems||0}.`,`Semantic items: ${status.semanticRetrieval.counts.indexedItems||0}.`]; const warnings=[]; if(!status.training.corpus.counts.approved) warnings.push("Mangler godkjent corpus."); if(!status.retrieval.counts.indexedItems) warnings.push("Retrieval-index er ikke bygget."); if(!["working","strong"].includes(status.aiLoopAudit.status)) warnings.push("Ingen nylig fungerende AI Loop Audit."); return { ok: status.overall.score>=50 && !warnings.length, score:status.overall.score, findings, warnings, recommendations:status.recommendations }; }
  function previewText(preview){ return [preview?.summary,...asArray(preview?.bullets),preview?.nextStep?`Neste steg: ${preview.nextStep}`:""].filter(Boolean).join("\n"); }
  function runFullControlTest(options={}){ const query=asText(options.query)||DEFAULT_QUERY; const personalContext=safe(()=>global.AHAChatPersonalContext?.buildMessageContext?.(query,options),null); const retrieval=safe(()=>global.AHAPersonalRetrieval?.buildRagContext?.(query,{...options,forceLexical:true}),null); const semanticRetrieval=safe(()=>global.AHASemanticRetrieval?.buildSemanticRagContext?.(query,options),null); const answerPackage=safe(()=>global.AHAPersonalAnswerComposer?.buildAnswerPackage?.(query,options),null); const preview=answerPackage?.localPreview || safe(()=>global.AHAPersonalAnswerComposer?.composeLocalAnswerPreview?.(answerPackage?.context||answerPackage),null); const answerEvaluation=safe(()=>global.AHAPersonalAnswerEvaluation?.evaluateAnswer?.(query,previewText(preview),answerPackage,options),null); if(answerEvaluation) safe(()=>global.AHAPersonalAnswerEvaluation?.saveEvaluation?.(answerEvaluation),null); const aiLoopAudit=safe(()=>global.AHAPersonalAiLoopAudit?.runAudit?.({ ...options, query }),null); const result={ generatedAt:now(options), query, personalContext, retrieval, semanticRetrieval, answerPackage, localPreview:preview, answerEvaluation, aiLoopAudit, summary:`Kontrolltest: ${(asArray(retrieval?.results).length)} lexical treff, ${(asArray(semanticRetrieval?.results).length)} semantic treff, evaluering ${num(answerEvaluation?.score)}/100.`, ok:Boolean(answerPackage||retrieval||semanticRetrieval) }; return result; }
  function saveLastControlStatus(status){ try{ global.localStorage?.setItem(STORAGE_KEY, JSON.stringify(status)); }catch{} return status; }
  function loadLastControlStatus(){ try{ return JSON.parse(global.localStorage?.getItem(STORAGE_KEY)||"null"); }catch{return null;} }
  global.AHAPersonalAiControl={ VERSION, STORAGE_KEY, DEFAULT_QUERY, buildControlStatus, collectModuleStatus, buildRecommendations, getNextAction, runQuickHealthCheck, runFullControlTest, saveLastControlStatus, loadLastControlStatus };
})(typeof window !== "undefined" ? window : globalThis);
