// Åpne Knowledge Workbench → knowledge-workbench.html
// AHA Personal AI Dashboard V1 – UI for Personal AI Control Panel.
(function(global){"use strict"; const doc=global.document; function $(id){return doc&&doc.getElementById(id);} function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");} function arr(v){return Array.isArray(v)?v:[];} function api(){return global.AHAPersonalAiControl;} let lastStatus=null;
function renderOverall(status){const m=$("personal-ai-overall"); if(!m)return; const n=status.nextAction||{}; m.innerHTML=`<div class="aha-training-stats"><div class="aha-mini-stat"><strong>${esc(status.overall.label)}</strong><span>Status</span></div><div class="aha-mini-stat"><strong>${Number(status.overall.score)||0}/100</strong><span>Score</span></div><div class="aha-mini-stat"><strong>${esc(status.overall.level)}</strong><span>Level</span></div></div><p>${esc(status.summary)}</p><p class="module-meta"><strong>Neste handling:</strong> ${esc(n.label)} — ${esc(n.description)}</p>${n.href?`<a class="aha-tile-btn aha-tile-btn-primary" href="${esc(n.href)}">${esc(n.label)}</a>`:""}`;}
function renderModules(status){const m=$("personal-ai-modules"); if(!m)return; const map=["metaInsightsMemory","trainingCorpus","trainingExamples","personalModelReadiness","chatPersonalContext","personalRetrieval","semanticRetrieval","personalAiLoopAudit","personalAnswerComposer","personalAnswerEvaluation"]; m.innerHTML=map.map(k=>{const x=status.modules[k]; const counts=Object.entries(x.counts||{}).slice(0,4).map(([a,b])=>`${a}: ${b}`).join(" · "); return `<article class="aha-panel"><h3>${esc(x.label)}</h3><p><strong>${esc(x.status)}</strong> · ${Number(x.score)||0}/100</p><p class="module-meta">${esc(counts||"ingen teller")}</p><p>${esc(arr(x.notes)[0]||"")}</p></article>`;}).join("");}
function renderRecommendations(status){const m=$("personal-ai-recommendations"); if(m)m.innerHTML=arr(status.recommendations).map(r=>`<li>${esc(r)}</li>`).join("");}
function renderEmpty(status){const m=$("personal-ai-empty"); if(m)m.hidden=Boolean(status.overall.score>0);}
function refresh(){ if(!api())return; lastStatus=api().buildControlStatus(); renderOverall(lastStatus); renderModules(lastStatus); renderRecommendations(lastStatus); renderEmpty(lastStatus); }
function resultCount(x){return arr(x&&x.results).length;} function renderTest(result){const m=$("personal-ai-result"); if(!m)return; const sources=arr(result.answerPackage?.context?.selectedSources).slice(0,6).map(s=>`<li>${esc(s.title)} <small>${esc(s.sourceType||s.source||"")}</small></li>`).join(""); m.innerHTML=`<h3>Resultat fra full kontrolltest</h3><p><strong>Query:</strong> ${esc(result.query)}</p><div class="aha-training-stats"><div class="aha-mini-stat"><strong>${resultCount(result.retrieval)}</strong><span>Lexical treff</span></div><div class="aha-mini-stat"><strong>${resultCount(result.semanticRetrieval)}</strong><span>Semantic treff</span></div><div class="aha-mini-stat"><strong>${Number(result.answerPackage?.status?.selectedSourceCount)||0}</strong><span>Selected sources</span></div><div class="aha-mini-stat"><strong>${Number(result.answerEvaluation?.score)||0}/100</strong><span>Evaluation</span></div><div class="aha-mini-stat"><strong>${Number(result.aiLoopAudit?.score)||0}/100</strong><span>Audit</span></div></div><ul>${sources||"<li>Ingen valgte kilder.</li>"}</ul><p>${esc(result.summary)}</p><details><summary>Tekniske detaljer</summary><pre>${esc(JSON.stringify(result,null,2)).slice(0,6000)}</pre></details>`;}
function setMessage(t){const m=$("personal-ai-message"); if(m)m.textContent=t||"";} function bind(){doc?.addEventListener("click",e=>{const b=e.target; if(!(b instanceof global.HTMLElement))return; const a=b.getAttribute("data-personal-ai-action"); if(!a||!api())return; if(a==="build_retrieval_index"){const r=global.AHAPersonalRetrieval?.refreshRetrievalIndex?.(); setMessage(`Personlig søkeindeks bygget med ${Number(r?.stats?.total)||0} items.`); refresh();} if(a==="build_semantic_index"){const r=global.AHASemanticRetrieval?.refreshSemanticIndex?.(); setMessage(`Semantisk søkeindeks bygget med ${Number(r?.stats?.total)||0} items.`); refresh();} if(a==="run_ai_loop_audit"){const r=global.AHAPersonalAiLoopAudit?.runAudit?.(); setMessage(`AI-loop audit: ${r?.status||"ukjent"}, ${Number(r?.score)||0}/100.`); refresh();} if(a==="test_answer_composer"){const r=global.AHAPersonalAnswerComposer?.buildAnswerPackage?.(api().DEFAULT_QUERY); setMessage(`Answer Composer: ${r?.status?.intent||"unknown"}, ${Number(r?.status?.selectedSourceCount)||0} kilder.`); refresh();} if(a==="test_answer_evaluation"){const r=api().runFullControlTest(); renderTest(r); setMessage("Answer Evaluation testet via full kontrolltest."); refresh();} if(a==="full_control_test"){const r=api().runFullControlTest(); renderTest(r); setMessage("Full kontrolltest fullført."); refresh();}});}
function init(){bind(); refresh();} const out={init,refresh,renderOverall,renderModules,renderRecommendations,renderTest}; if(typeof module!=="undefined"&&module.exports)module.exports=out; global.AHAPersonalAiDashboard=out; if(doc){doc.readyState==="loading"?doc.addEventListener("DOMContentLoaded",init):init();}})(typeof window!=="undefined"?window:globalThis);
