// AHA Source Connectors V1 – conditional adapters from real AHA sources to Data Intake.
(function (global) {
  "use strict";
  const VERSION = "v1";
  const LAST_SCAN_KEY = "aha_source_connectors_last_scan_v1";
  const SOURCES = ["aha_chat","sync_hub","aha_music","history_go","aha_notes","aha_feed","aha_articles","meta_insights","personal_ai","training_suggestions"];
  const SOURCE_KEYS = {
    aha_chat:["aha_chat_sessions_v1","aha_chat_history_v1","aha_chat_messages_v1","aha_chat_log_v1","aha_pending_chat_prompt_v1"],
    sync_hub:["aha_sync_hub_candidates_v1","aha_manual_sync_candidates_v1","aha_sync_candidates_v1"],
    aha_music:["aha_music_library_v1","aha_music_tracks_v1","aha_music_artists_v1","aha_music_playlists_v1","aha_music_history_go_bridge_v1"],
    history_go:["aha_historygo_bridge_v1","aha_history_go_discoveries_v1","aha_historygo_discoveries_v1"],
    aha_notes:["aha_notes_v1"], aha_feed:["aha_feed_posts_v1"], aha_articles:["aha_articles_v1"],
    meta_insights:["aha_meta_insights_memory_v1","aha_insight_chamber_v1"], personal_ai:["aha_personal_answer_evaluations_v1"], training_suggestions:["aha_personal_answer_evaluations_v1"]
  };
  const DEFINITIONS = {
    aha_chat:{title:"AHA Chat",href:"chat.html",planned:true,reason:"Chat persistence er ikke aktiv ennå."},
    sync_hub:{title:"Sync Hub",href:"index.html#aha-sync-hub-status",planned:true,globals:["AHASyncHub","AHASyncCandidateBuilder","AHAManualSyncDryRunTargetAdapter"]},
    aha_music:{title:"AHA Music",href:"music.html",planned:true,globals:["AHAMusic","AHAMusicCanon","AHAMusicHistoryGoBridge","AHAMusicHistoryGoDiscovery"]},
    history_go:{title:"History Go",href:"historygo.html",planned:true,globals:["AHAHistoryGoImport","AHAHistoryGoStatus"]},
    aha_notes:{title:"Notes",href:"notes.html",missing:true,globals:["AHANotes"]},
    aha_feed:{title:"Feed",href:"feed.html",missing:true,globals:["AHAFeed"]},
    aha_articles:{title:"Articles",href:"articles.html",missing:true,globals:["AHAAvisa"]},
    meta_insights:{title:"Meta Insights",href:"insights.html",globals:["AHAMetaInsightsMemory","AHAMetaInsightsAgent"]},
    personal_ai:{title:"Personal AI evaluations",href:"personal-ai.html",globals:["AHAPersonalAnswerEvaluation"]},
    training_suggestions:{title:"Training suggestions",href:"training.html",globals:["AHAPersonalAnswerEvaluation"]}
  };
  function storage(){ try { return global.localStorage || null; } catch { return null; } }
  function parse(raw, fb){ try { const v=JSON.parse(raw); return v == null ? fb : v; } catch { return fb; } }
  function arr(v){ return Array.isArray(v) ? v : []; }
  function obj(v){ return v && typeof v === "object" && !Array.isArray(v) ? v : {}; }
  function text(v){ return String(v ?? "").trim(); }
  function now(options={}){ return new Date(options.now || Date.now()).toISOString(); }
  function unique(v){ const seen=new Set(); return arr(v).concat(typeof v === "string" ? v.split(",") : []).map(x=>text(x?.label||x?.name||x)).filter(Boolean).filter(x=>{const k=x.toLowerCase(); if(seen.has(k)) return false; seen.add(k); return true;}); }
  function hash(value){ const s=text(value).replace(/\s+/g," ").toLowerCase(); let h=5381; for(let i=0;i<s.length;i++) h=((h<<5)+h+s.charCodeAt(i))>>>0; return `sc_${h.toString(36)}_${s.length}`; }
  function readKey(key){ const raw=storage()?.getItem(key); return raw ? parse(raw,null) : null; }
  function extractList(data){ if(Array.isArray(data)) return data; const o=obj(data); return arr(o.items).concat(arr(o.records),arr(o.candidates),arr(o.messages),arr(o.tracks),arr(o.artists),arr(o.playlists),arr(o.discoveries),arr(o.places),arr(o.posts),arr(o.articles),arr(o.notes),arr(o.evaluations)).filter(Boolean); }
  function hasRuntimeSource(source){ if(source==="aha_chat" && global.AHAChatPersistence) return true; const def=DEFINITIONS[source]||{}; if(arr(def.globals).some(k=>Boolean(global[k]))) return true; return arr(SOURCE_KEYS[source]).some(k=>Boolean(storage()?.getItem(k))); }
  function keyCount(source){ if(source==="aha_chat" && global.AHAChatPersistence?.collectChatStats){ return Number(global.AHAChatPersistence.collectChatStats().messages)||0; } return arr(SOURCE_KEYS[source]).reduce((sum,k)=>sum + extractList(readKey(k)).length,0); }
  function capabilities(source, active){ return { canScan:Boolean(active), canImportText:["aha_chat","aha_notes","aha_feed","aha_articles","meta_insights","personal_ai","training_suggestions","sync_hub"].includes(source), canImportMetadata:true, canSuggestTrainingCorpus:source!=="aha_music"||active, canSuggestHistoryGo:["aha_music","history_go"].includes(source), canSuggestMusicCanon:source==="aha_music" }; }
  function statusFor(source){
    const def=DEFINITIONS[source]; const runtime=hasRuntimeSource(source); const count=keyCount(source); let status=runtime?(count?"active":"empty"):(def.missing?"missing":def.planned?"planned":"missing");
    if(source==="aha_chat" && global.AHAChatPersistence) status="active";
    if(source==="personal_ai" && global.AHAPersonalAnswerEvaluation) status="active";
    if(source==="meta_insights" && global.AHAMetaInsightsMemory) status="active";
    const available=["active","empty"].includes(status);
    return { id:`connector_${source}`, title:def.title, source, status, available, itemCount:count, lastScannedAt:text(parse(storage()?.getItem(LAST_SCAN_KEY)||"{}",{})[source]), href:def.href, reason: status==="planned"||status==="missing"?def.reason||`${def.title} runtime-data finnes ikke ennå.`:(status==="empty"?`${def.title} finnes, men har ingen importbare items ennå.`:"Kilden finnes og kan skannes."), capabilities:capabilities(source, status==="active") };
  }
  function collectConnectorStatus(options={}){ const connectors=SOURCES.map(statusFor); const active=connectors.filter(c=>c.status==="active").length, planned=connectors.filter(c=>c.status==="planned").length, missing=connectors.filter(c=>c.status==="missing").length; const totalAvailable=connectors.filter(c=>c.available).length; return { generatedAt:now(options), connectors, active, planned, missing, totalAvailable, summary:`${active} active, ${planned} planned, ${missing} missing source connectors.` }; }
  function sourceTypeFor(source,c){ const o=obj(c); if(source==="personal_ai") return o.trainingSuggestion?"training_suggestion":"answer_evaluation"; if(source==="sync_hub") return "sync_candidate"; if(source==="aha_chat") return "chat_message"; if(source==="aha_notes") return "note"; if(source==="aha_feed") return "feed_post"; if(source==="aha_articles") return "article"; if(source==="meta_insights") return "meta_summary"; if(source==="history_go") return /place/i.test(text(o.type||o.sourceType))?"history_go_place":"history_go_discovery"; if(source==="aha_music") return /artist/i.test(text(o.type||o.sourceType))?"artist":/playlist/i.test(text(o.type||o.sourceType))?"playlist":"music_track"; return "manual_text"; }
  function targetsFor(source){ return source==="personal_ai"||source==="training_suggestions"?["training_corpus","personal_retrieval"]:source==="meta_insights"?["meta_insights_memory","training_corpus","personal_retrieval"]:source==="sync_hub"?["training_corpus","personal_retrieval","sync_hub_review"]:source==="aha_music"?["aha_music_canon","history_go_discovery","training_corpus"]:source==="history_go"?["history_go_discovery","training_corpus","personal_retrieval"]:source==="aha_chat"?["training_corpus","personal_retrieval","meta_insights_memory"]:["training_corpus","personal_retrieval"]; }
  function normalizeSourceCandidate(candidate, source){ const o=obj(candidate); const sourceType=text(o.sourceType||o.source_type)||sourceTypeFor(source,o); const body=text(o.text||o.body||o.content||o.message||o.answer||o.output||o.summary||o.description||o.trainingSuggestion?.reason||o.training_suggestion||o.draftExample?.output||o.claimText||o.name||o.title); return { source, sourceId:text(o.sourceId||o.source_id||o.id||o.claimId)||`${source}:${hash(JSON.stringify(o).slice(0,700))}`, sourceType, title:text(o.title||o.name||o.question||o.input||o.claimText)||sourceType, text:body, summary:text(o.summary||o.description)||body.slice(0,220), language:text(o.language)||(/[æøå]/i.test(body)?"no":"unknown"), project:text(o.project), tags:unique(o.tags), concepts:unique(o.concepts), entities:unique(o.entities), linkedObjects:arr(o.linkedObjects||o.linked_objects), suggestedTargets:targetsFor(source).map(target=>({target,confidence:.8,reason:`Source connector ${source}`})), status:o.status || (source==="aha_chat"?"review":"new"), consent:{ useForMemory:true, useForTrainingCorpus:false, useForRetrieval:true, useForStyle:false, useForFineTuning:false, useForHistoryGo:source==="history_go", useForMusicCanon:source==="aha_music" }, priority:Number(o.priority)||0, meta:{ sourceConnector:VERSION, rawType:text(o.type), generatedAt:now() } }; }
  function pushItemsToDataIntake(items){ const api=global.AHADataIntake; const result={ ok:Boolean(api?.addIntakeItem), added:0, skipped:0, failed:0 }; if(!api?.addIntakeItem){ result.skipped=arr(items).length; return result; } arr(items).forEach(item=>{ try { const added=api.addIntakeItem(item); if(added) result.added++; else result.skipped++; } catch { result.failed++; } }); result.ok=result.failed===0; return result; }
  function personalCandidates(){ const api=global.AHAPersonalAnswerEvaluation; const seen=new Set(); return arr(api?.loadEvaluations?.()).flatMap((e,i)=>{ const out=[]; const ts=obj(e.trainingSuggestion); if(ts.shouldCreateExample && ts.draftExample){ out.push({...ts.draftExample, id:`${e.id||i}:draft`, sourceType:"training_suggestion", title:`Training suggestion: ${ts.suggestedTaskType||"answer"}`, meta:{evaluationId:e.id, score:e.score}}); } if(text(e.summary)||text(e.answerText)) out.push({...e, id:`${e.id||i}:summary`, sourceType:"answer_evaluation", text:text(e.summary||e.answerText), title:`Answer evaluation ${e.score||0}/100`}); return out.filter(x=>{ const k=hash(`${x.sourceType}:${x.input||""}:${x.output||x.text||""}`); if(seen.has(k)) return false; seen.add(k); return text(x.text||x.output||x.summary).length>20; }); }); }
  function metaCandidates(){ const api=global.AHAMetaInsightsMemory; const s=obj(api?.summarizeMemory?.()); const pack=obj(api?.buildMemoryPack?.()); const claims=[...arr(s.confirmedClaims),...arr(s.importantClaims)].map(c=>({...obj(c), sourceType:"meta_summary", text:text(c.claimText||c.text||c), title:"Meta insight claim"})); const active=[...arr(s.activeSelfModel?.activePatterns),...arr(s.activeSelfModel?.activeProjects),...arr(s.activeSelfModel?.activeTensions)].map((x,i)=>({id:`active_${i}`,sourceType:"meta_summary",title:"Active self model",text:text(x?.label||x?.title||x?.name||x)})); const compact=[...arr(pack.confirmed_claims),...arr(pack.important_claims)].map((x,i)=>({id:`pack_${i}`,sourceType:"meta_summary",title:"Meta memory summary",text:x})); return [...claims,...active,...compact].filter(x=>text(x.text).length>15); }
  function localCandidates(source){ return arr(SOURCE_KEYS[source]).flatMap(key=>extractList(readKey(key)).map((x,i)=>({...obj(x), id:text(x?.id)||`${key}:${i}`, meta:{storageKey:key}}))); }
  function scanSource(source, options={}){ if(!SOURCES.includes(source)) return {ok:false,source,added:0,skipped:0,total:0,items:[],warnings:["unknown_source"]}; let raw=[]; const warnings=[]; try { if(source==="personal_ai"||source==="training_suggestions") raw=personalCandidates(); else if(source==="meta_insights") raw=metaCandidates(); else if(source==="aha_chat" && global.AHAChatPersistence?.buildChatIntakeCandidates) raw=arr(global.AHAChatPersistence.buildChatIntakeCandidates(options).items); else raw=localCandidates(source); } catch(e){ return {ok:false,source,added:0,skipped:0,total:0,items:[],warnings:[text(e.message)||"scan_error"]}; }
    const items=raw.map(c=>normalizeSourceCandidate(c, source)).filter(i=>text(i.text||i.summary).length >= (source==="aha_chat"?24:10)); const pushed=options.dryRun?{added:0,skipped:items.length,failed:0}:pushItemsToDataIntake(items); const scans=parse(storage()?.getItem(LAST_SCAN_KEY)||"{}",{}); scans[source]=now(options); try{ storage()?.setItem(LAST_SCAN_KEY,JSON.stringify(scans)); }catch{} if(!items.length) warnings.push("no_importable_items"); return { ok:pushed.failed===0, source, added:pushed.added, skipped:pushed.skipped, total:items.length, items, warnings }; }
  function scanAllSources(options={}){ const status=collectConnectorStatus(options); const active=status.connectors.filter(c=>c.status==="active"); const results=active.map(c=>scanSource(c.source,options)); const warnings=results.flatMap(r=>arr(r.warnings).map(w=>`${r.source}:${w}`)); return { ok:results.every(r=>r.ok), generatedAt:now(options), results, totalAdded:results.reduce((s,r)=>s+r.added,0), totalSkipped:results.reduce((s,r)=>s+r.skipped,0), warnings }; }
  global.AHASourceConnectors={ VERSION, LAST_SCAN_KEY, SOURCE_KEYS, collectConnectorStatus, scanAllSources, scanSource, pushItemsToDataIntake, normalizeSourceCandidate };
})(typeof window !== "undefined" ? window : globalThis);
