// ahaInsta.js
(function () {
  "use strict";
  const KEY="aha_insta_posts_v1";
  const load=()=>{try{const p=JSON.parse(localStorage.getItem(KEY)||"[]"); return Array.isArray(p)?p:[];}catch{return[];}};
  const save=(items)=>localStorage.setItem(KEY,JSON.stringify(Array.isArray(items)?items:[]));
  const active=(items)=>(Array.isArray(items)?items:[]).filter((x)=>!x?.deleted_at);
  const esc=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
  const type=(src)=>/\.(mp4|webm|ogg)(\?|#|$)/i.test(String(src||""))?"video":"image";
  function persistPost(post){window.AHARepository?.saveInstaPost?.(post).then((r)=>{if(r?.ok===false&&r.error)console.warn("AHAInsta: database-save feilet",r.error);});}
  function renderMedia(src){const v=String(src||"").trim(); if(!v)return""; return type(v)==="video"?`<video src="${esc(v)}" controls></video>`:`<img src="${esc(v)}" alt="" loading="lazy" />`;}
  function render(source){const m=document.getElementById("insta-list"); if(!m)return; const posts=active(Array.isArray(source)?source:load()); m.innerHTML=posts.length?posts.map((p)=>`<article class="module-card"><h3>${esc(p.title||"Uten tittel")}</h3>${renderMedia(p.src)}<p>${esc(p.caption||"")}</p><div class="module-meta">${esc(p.created_at||"")}${p.last_source_event_id?` · source: ${esc(p.last_source_event_id)}`:""}</div><div class="module-actions"><button type="button" data-action="delete" data-id="${esc(p.id)}">Slett</button></div></article>`).join(""):'<p>Ingen Insta-poster ennå.</p>';}
  function addPost(input){const post={id:`insta_${Date.now()}_${Math.floor(Math.random()*100000)}`,title:String(input.title||"").trim(),src:String(input.src||"").trim(),caption:String(input.caption||"").trim(),content_type:type(input.src),tags:Array.isArray(input.tags)?input.tags:[],meta:{},created_at:new Date().toISOString(),deleted_at:null,last_source_event_id:null}; if(!post.title&&!post.caption&&!post.src) return null; const res=window.AHAIngest?.ingest?.({source_type:"insta_post",source_app:"aha_insta",content_type:post.content_type,title:post.title,text:[post.title,post.caption].filter(Boolean).join("\n"),user_created:true,imported:false,created_at:post.created_at,meta:{insta_post_id:post.id,src:post.src}}); if(res?.sourceEvent?.id) post.last_source_event_id=res.sourceEvent.id; const posts=load(); posts.unshift(post); save(posts); persistPost(post); render(posts); return post;}
  function deletePost(id){const posts=load(); const i=posts.findIndex((p)=>p.id===id&&!p.deleted_at); if(i<0)return false; posts[i]={...posts[i],deleted_at:new Date().toISOString()}; save(posts); persistPost(posts[i]); render(posts); return true;}
  function bind(){const form=document.getElementById("insta-form"); if(form){form.addEventListener("submit",(e)=>{e.preventDefault(); const t=document.getElementById("insta-title"); const s=document.getElementById("insta-src"); const c=document.getElementById("insta-caption"); addPost({title:t?.value,src:s?.value,caption:c?.value}); if(t)t.value=""; if(s)s.value=""; if(c)c.value="";});} document.getElementById("insta-list")?.addEventListener("click",(e)=>{const b=e.target.closest("button[data-action='delete'][data-id]"); if(b) deletePost(b.dataset.id);}); render();}
  window.AHAInsta={load,save,addPost,deletePost,render}; if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",bind); else bind();
})();
