const assert = require('assert'); const fs = require('fs'); const vm = require('vm');
function ctx(extra={}){ const store={}; const c={console, module:{exports:{}}, exports:{}, localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>{store[k]=String(v)},removeItem:k=>delete store[k]}, ...extra}; c.globalThis=c; c.window=c; return c; }
function run(file,c){ vm.runInNewContext(fs.readFileSync(file,'utf8'), c, {filename:file}); return c; }
{ const c=ctx(); run('js/ahaKnowledgeCuration.js',c); assert.deepEqual(c.AHAKnowledgeCuration.loadCurationItems(),[]); }
{ const c=ctx(); run('js/ahaKnowledgeCuration.js',c); const i=c.AHAKnowledgeCuration.normalizeCurationItem({title:'T',concepts:'AHA, AI'}); assert.equal(i.type,'knowledge_curation_item'); assert.deepEqual(i.concepts,['AHA','AI']); }
{ const c=ctx({AHADataIntake:{loadQueue:()=>[{id:'i1',status:'review',source:'manual',sourceType:'manual_text',title:'AHA Personal AI',text:'AHA Personal AI prosjekt med mye tekst om chat approval og Training Corpus.',project:'AHA',concepts:['Personal AI'],tags:['training'],consent:{useForRetrieval:true}}]}}); run('js/ahaKnowledgeCuration.js',c); const r=c.AHAKnowledgeCuration.buildCurationItemsFromIntake(); assert.equal(r.created,1); assert.equal(c.AHAKnowledgeCuration.loadCurationItems().length,1); }
{ const c=ctx(); run('js/ahaKnowledgeCuration.js',c); const clusters=c.AHAKnowledgeCuration.clusterIntakeItems([{id:'1',project:'AHA',concepts:['AI'],title:'one',text:'alpha'},{id:'2',project:'AHA',concepts:['AI'],title:'two',text:'beta'}]); assert.equal(clusters.length,1); }
{ const c=ctx(); run('js/ahaKnowledgeCuration.js',c); const d=c.AHAKnowledgeCuration.detectDuplicates([{id:'1',source:'chat',sourceId:'m1',text:'Same text'},{id:'2',source:'chat',sourceId:'m1',text:'Same text'}]); assert.ok(d.duplicateGroups.length>=1); }
{ const c=ctx(); run('js/ahaKnowledgeCuration.js',c); const t=c.AHAKnowledgeCuration.suggestTargetsForCluster({project:'AHA',items:[{text:'Lang prosjekttekst om AHA og Training Corpus med nok innhold til corpus.'}]}); assert.ok(t.includes('training_corpus')); }
{ const c=ctx(); run('js/ahaKnowledgeCuration.js',c); const p=c.AHAKnowledgeCuration.prioritizeCurationItems([{title:'a',theme:'AHA',sourceItemIds:['1'],suggestedTargets:['training_corpus']},{title:'b',theme:'AHA',sourceItemIds:['2'],suggestedTargets:['training_corpus']}]); assert.ok(p.some(i=>i.priority==='high')); }
{ const c=ctx(); run('js/ahaKnowledgeCuration.js',c); const [i]=c.AHAKnowledgeCuration.saveCurationItems([{title:'Approve'}]); assert.equal(c.AHAKnowledgeCuration.approveCurationItem(i.id).status,'approved'); }
{ const c=ctx(); run('js/ahaKnowledgeCuration.js',c); const items=c.AHAKnowledgeCuration.saveCurationItems([{title:'A',sourceItemIds:['i1'],concepts:['x']},{title:'B',sourceItemIds:['i2'],concepts:['y']}]); const m=c.AHAKnowledgeCuration.mergeCurationItems(items.map(i=>i.id)); assert.deepEqual(m.sourceItemIds.sort(),['i1','i2']); assert.deepEqual(m.concepts.sort(),['x','y']); }
{ let called=0; const c=ctx({AHATrainingCorpus:{addCorpusItem:(i)=>{called++; return {id:'c1',...i}}}}); run('js/ahaKnowledgeCuration.js',c); const [i]=c.AHAKnowledgeCuration.saveCurationItems([{title:'Send',status:'approved',summary:'summary',suggestedTargets:['training_corpus']}]); assert.ok(c.AHAKnowledgeCuration.sendToTrainingCorpus(i.id).ok); assert.equal(called,1); }
{ const c=ctx(); run('js/ahaKnowledgeCuration.js',c); c.AHAKnowledgeCuration.saveCurationItems([{title:'A',status:'approved',priority:'high',suggestedTargets:['training_corpus','meta_insights_memory']}]); const s=c.AHAKnowledgeCuration.collectCurationStats(); assert.equal(s.approved,1); assert.equal(s.highPriority,1); }
const html=fs.readFileSync('curation.html','utf8'); ['js/ahaDataIntake.js','js/ahaKnowledgeCuration.js','js/ahaTrainingCorpus.js','js/ahaTrainingExamples.js','js/metaInsightsMemory.js','js/ahaProductIntegration.js','js/ahaPersonalAiControl.js','js/ahaKnowledgeCurationDashboard.js'].forEach(x=>assert.ok(html.includes(x),x));
assert.ok(fs.readFileSync('js/ahaModules.js','utf8').includes('knowledge-curation'));
assert.ok(fs.readFileSync('js/ahaDataIntakeDashboard.js','utf8').includes('AHAKnowledgeCuration'));
assert.ok(fs.readFileSync('js/ahaTrainingDashboard.js','utf8').includes('handleCurationImport'));
assert.ok(fs.readFileSync('js/ahaProductIntegration.js','utf8').includes('knowledgeCuration'));
assert.ok(fs.readFileSync('js/ahaPersonalAiControl.js','utf8').includes('knowledgeCuration'));
{ const c=ctx({AHAKnowledgeCuration:{buildCurationSummary:()=>({available:true,total:1,reviewCount:1,highPriority:0,duplicateGroups:0,trainingReady:0,topThemes:[],nextAction:'test'})}}); run('js/metaInsightsAgent.js',c); const ac=c.AHAMetaInsightsAgent.buildAgentContext({}); assert.ok(ac.knowledgeCurationPack.available); }
{ const c=ctx({AHATrainingCorpus:{addCorpusItem:()=>{throw new Error('should not auto import')}}}); run('js/ahaKnowledgeCuration.js',c); c.AHAKnowledgeCuration.saveCurationItems([{title:'No auto',status:'review',suggestedTargets:['training_corpus']}]); assert.equal(c.AHAKnowledgeCuration.collectCurationStats().trainingReady,0); }
console.log('aha-knowledge-curation tests passed');
