const assert = require("assert");
const fs = require("fs");

const audit = JSON.parse(fs.readFileSync("ops/evaluation/aha-projection-product-agent-quality-review-v2.json", "utf8"));
const humanReview = JSON.parse(fs.readFileSync("ops/evaluation/aha-projection-product-human-review-v2.json", "utf8"));
const browserSpec = fs.readFileSync("tests/browser/aha-projection-product-browser-evaluation-v2.spec.cjs", "utf8");
const liveArchive = JSON.parse(fs.readFileSync("ops/evaluation/aha-projection-product-live-review-archive-v2.json", "utf8"));

assert.equal(audit.schema, "aha_projection_product_agent_quality_review_v2");
assert.equal(audit.scope.cases, 27);
assert.equal(audit.scope.expected_visible, 24);
assert.equal(audit.scope.expected_suppressed, 3);
assert.equal(audit.scope.independent_human_review_completed, false);
assert.equal(audit.browser_evaluation.cases, 27);
assert.equal(audit.browser_evaluation.independent_human_review_completed, false);
assert.equal(audit.browser_evaluation.ipad_webkit_gate, true);
assert.equal(audit.latest_live_gate.chat_submission_count, 29);
assert.equal(audit.latest_live_gate.chat_2xx_count, 29);
assert.equal(audit.latest_live_gate.upstream_failure, null);
assert.equal(audit.latest_live_gate.fallback_product_output_is_live_quality_evidence, false);
assert.equal(audit.latest_live_gate.gate_status, "live_transport_and_agent_usefulness_assessment_passed");
assert.ok(audit.latest_live_gate.coverage_case_qualified_preview_share >= 0.8);
assert.equal(audit.latest_live_gate.critical_provenance_error_count, 0);
assert.equal(audit.latest_live_gate.guarded_preview_write_count, 0);
assert.equal(audit.independent_usefulness_assessment.status, "complete");
assert.equal(audit.independent_usefulness_assessment.authority, "independent_agent_quality_review_not_human_attestation");
assert.deepEqual(audit.independent_usefulness_assessment.verified_findings.map((entry) => entry.case_id).sort(), ["conflict_tourism", "data_bus"]);
assert.equal(audit.independent_usefulness_assessment.scope_boundary.analysis_quality_gate_changed, false);
assert.equal(audit.independent_usefulness_assessment.scope_boundary.product_builder_changed, false);
assert.equal(audit.independent_usefulness_assessment.scope_boundary.human_review_attested, false);
assert.equal(audit.observation_probe.pull_request, 882);
assert.equal(audit.observation_probe.disposition, "closed_without_merge");
assert.equal(audit.remediation.pull_request, 884);
assert.equal(audit.remediation.strategy, "read_only_source_bound_usefulness_refinement");
assert.equal(audit.current_human_review_projection.pull_request, 958);
assert.equal(audit.current_human_review_projection.mode, "current_read_only_projection_from_archived_live_insights");
assert.equal(audit.current_human_review_projection.current_product_code_applied, true);
assert.equal(audit.current_human_review_projection.new_model_calls_required, false);
assert.equal(audit.current_human_review_projection.human_scores_autofilled, false);
assert.ok(audit.observed_defects.some((entry) => entry.id === "generic_path_copy" && entry.severity === "high"));
assert.ok(audit.observed_defects.some((entry) => entry.id === "low_information_display_anchor" && entry.severity === "high"));
assert.deepEqual(audit.evaluation_limitations.semantic_document_observed_arrays_empty, ["concepts", "claims", "relations", "tensions", "candidate_insights"]);
assert.equal(audit.evaluation_limitations.semantic_document_quality_status, "shadow_claims_relations_pending");
assert.equal(audit.release_boundary.independent_human_review_required, true);
assert.equal(audit.release_boundary.human_usefulness_gate, "open");
assert.equal(audit.release_boundary.automatic_persistence_allowed, false);
assert.equal(audit.release_boundary.projection_store_write_open, false);
assert.equal(audit.release_boundary.normal_chat_automatic_persistence_open, false);
assert.equal(audit.release_boundary.remote_write_open, false);

assert.equal(humanReview.status, "agent_pre_review_complete_independent_human_review_open");
assert.equal(humanReview.release_rule.independent_human_review_required, true);
assert.equal(humanReview.release_rule.minimum_acceptable_share, 0.8);
assert.equal(humanReview.release_rule.critical_provenance_errors_allowed, 0);
assert.equal(humanReview.release_rule.automatic_persistence_allowed, false);
assert.equal(humanReview.release_rule.reviewer_attestation_required, true);
assert.equal(humanReview.rubric.acceptable_score_minimum, 4);
assert.equal(humanReview.archived_live_review_input.available, true);
assert.equal(humanReview.archived_live_review_input.new_model_calls_required, false);
assert.equal(humanReview.archived_live_review_input.reviewer_scores_autofilled, false);
assert.equal(humanReview.archived_live_review_input.review_projection_mode, "current_read_only_projection_from_archived_live_insights");
assert.equal(humanReview.archived_live_review_input.current_product_code_applied, true);
assert.equal(humanReview.review_workflow.explicit_draft_export, true);
assert.equal(humanReview.review_workflow.explicit_draft_import, true);
assert.equal(humanReview.review_workflow.automatic_browser_persistence, false);
assert.equal(humanReview.review_workflow.imported_scores_and_notes_restored, true);
assert.equal(humanReview.review_workflow.imported_human_attestation_restored, false);
assert.equal(humanReview.review_workflow.final_attestation_must_be_reconfirmed, true);
assert.equal(humanReview.review_workflow.canonical_rubric_rendered_in_review_surface, true);
assert.equal(humanReview.review_workflow.rubric_source, "ops/evaluation/aha-projection-product-human-review-v2.json");
assert.ok(humanReview.case_reviews.every((entry) => entry.review_status === "open"));

assert.equal(liveArchive.schema, "aha_projection_product_live_review_archive_v2");
assert.equal(liveArchive.workflow_run_id, 32633381518);
assert.equal(liveArchive.artifact_id, 9491725428);
assert.equal(liveArchive.corpus_cases, 27);
assert.equal(liveArchive.successful_chat_count, 29);
assert.equal(liveArchive.critical_transport_failures, 0);
assert.equal(liveArchive.critical_provenance_errors_in_archived_results, 0);
assert.equal(liveArchive.import_mode, "local_json_then_current_read_only_reprojection");
assert.equal(liveArchive.review_projection_mode, "current_read_only_projection_from_archived_live_insights");
assert.equal(liveArchive.current_product_code_applied, true);
assert.equal(liveArchive.new_model_calls_required, false);
assert.equal(liveArchive.independent_human_review_complete, false);
assert.equal(liveArchive.human_review_must_not_be_autofilled, true);
assert.equal(liveArchive.pull_request, 894);
assert.equal(liveArchive.semantic_shapes_applied, true);
assert.equal(liveArchive.product_shapes.lists, "thematic_membership_v2");
assert.equal(liveArchive.product_shapes.paths, "ordered_inquiry_v2");
assert.equal(liveArchive.product_shapes.mindmap, "ranked_hierarchy_v2");

assert.match(browserSpec, /aha_projection_product_live_backend_preflight_v3/);
assert.match(browserSpec, /preflightResponse\.ok\(\)/);
assert.match(browserSpec, /AHA_LIVE_PRODUCT_MODE \|\| "offline"/);
assert.match(browserSpec, /aha_insight_synthesis_cost_control_v1/);
assert.match(browserSpec, /successfulChatResponses\.length/);
assert.match(browserSpec, /backend_http_failures/);
assert.match(browserSpec, /initialUsefulCaseCoverage/);
assert.match(browserSpec, /runCases/);

console.log("aha-projection-product-agent-quality-review-v2.test.cjs: OK (agent remediation recorded; independent human gate remains open)");
