const assert = require("assert");
const fs = require("fs");

const audit = JSON.parse(fs.readFileSync("ops/evaluation/aha-projection-product-agent-quality-review-v2.json", "utf8"));
const humanReview = JSON.parse(fs.readFileSync("ops/evaluation/aha-projection-product-human-review-v2.json", "utf8"));
const browserSpec = fs.readFileSync("tests/browser/aha-projection-product-browser-evaluation-v2.spec.cjs", "utf8");
const liveArchive = JSON.parse(fs.readFileSync("ops/evaluation/aha-projection-product-live-review-archive-v2.json", "utf8"));

assert.equal(audit.schema, "aha_projection_product_agent_quality_review_v2");
assert.equal(audit.scope.cases, 27);
assert.equal(audit.scope.expected_visible, 24);
assert.equal(audit.scope.expected_suppressed, 3);
assert.equal(audit.scope.independent_human_review_completed, false);
assert.equal(audit.browser_evaluation.cases, 27);
assert.equal(audit.browser_evaluation.independent_human_review_completed, false);
assert.equal(audit.browser_evaluation.ipad_webkit_gate, true);
assert.match(audit.browser_evaluation.live_matrix, /minimum_80_percent_coverage_per_product_type/);
assert.equal(audit.latest_live_gate.chat_submission_count, 29);
assert.equal(audit.latest_live_gate.chat_2xx_count, 29);
assert.equal(audit.latest_live_gate.upstream_failure, null);
assert.equal(audit.latest_live_gate.fallback_product_output_is_live_quality_evidence, false);
assert.equal(audit.latest_live_gate.gate_status, "live_transport_and_agent_usefulness_assessment_passed");
assert.ok(audit.latest_live_gate.coverage_case_qualified_preview_share >= 0.8);
assert.equal(audit.latest_live_gate.critical_provenance_error_count, 0);
assert.equal(audit.latest_live_gate.guarded_preview_write_count, 0);
assert.equal(audit.independent_usefulness_assessment.status, "complete");
assert.equal(audit.independent_usefulness_assessment.authority, "independent_agent_quality_review_not_human_attestation");
assert.equal(audit.independent_usefulness_assessment.historical_coverage_rule, "at_least_one_qualified_product_per_coverage_case");
assert.equal(audit.independent_usefulness_assessment.current_release_coverage_rule, "at_least_80_percent_qualified_coverage_for_each_product_type");
assert.equal(audit.independent_usefulness_assessment.historical_gate_does_not_replace_current_per_product_release_gate, true);
assert.deepEqual(audit.independent_usefulness_assessment.verified_findings.map((entry) => entry.case_id).sort(), ["conflict_tourism", "data_bus"]);
assert.equal(audit.independent_usefulness_assessment.scope_boundary.analysis_quality_gate_changed, false);
assert.equal(audit.independent_usefulness_assessment.scope_boundary.product_builder_changed, false);
assert.equal(audit.independent_usefulness_assessment.scope_boundary.human_review_attested, false);
assert.equal(audit.observation_probe.pull_request, 882);
assert.equal(audit.observation_probe.disposition, "closed_without_merge");
assert.equal(audit.remediation.pull_request, 884);
assert.equal(audit.remediation.strategy, "read_only_source_bound_usefulness_refinement");
assert.equal(audit.current_human_review_projection.pull_request, 958);
assert.equal(audit.current_human_review_projection.mode, "current_read_only_projection_from_archived_live_insights");
assert.equal(audit.current_human_review_projection.current_product_code_applied, true);
assert.equal(audit.current_human_review_projection.human_score_denominator, "materialized_product_outputs_only");
assert.equal(audit.current_human_review_projection.missing_product_outputs_receive_human_scores, false);
assert.equal(audit.current_human_review_projection.current_reprojection_coverage_gate.coverage_case_count, 22);
assert.equal(audit.current_human_review_projection.current_reprojection_coverage_gate.minimum_qualified_product_share, 0.8);
assert.deepEqual(audit.current_human_review_projection.current_reprojection_coverage_gate.required_product_types, ["lists", "paths", "mindmap"]);
assert.equal(audit.current_human_review_projection.current_reprojection_coverage_gate.coverage_must_pass_per_product_type, true);
assert.equal(audit.current_human_review_projection.current_reprojection_coverage_gate.expected_suppressed_case_count, 3);
assert.equal(audit.current_human_review_projection.current_reprojection_coverage_gate.required_suppression_share, 1);
assert.equal(audit.current_human_review_projection.current_reprojection_coverage_gate.population_from_canonical_corpus, true);
assert.equal(audit.current_human_review_projection.current_reprojection_coverage_gate.must_pass_before_human_scoring, true);
assert.equal(audit.current_human_review_projection.current_reprojection_evidence.release_gate_passed, false);
assert.equal(audit.current_human_review_projection.current_reprojection_evidence.product_coverage.lists.qualified_case_share, 0.727273);
assert.equal(audit.current_human_review_projection.current_reprojection_evidence.product_coverage.paths.qualified_case_share, 0.818182);
assert.equal(audit.current_human_review_projection.current_reprojection_evidence.product_coverage.mindmap.qualified_case_share, 0.772727);
assert.equal(audit.current_human_review_projection.human_scoring_input_ready, false);
assert.equal(audit.current_human_review_projection.archived_evidence_superseded_by_post_archive_runtime_changes, true);
assert.equal(audit.current_human_review_projection.fresh_release_proof_required, true);
assert.equal(audit.current_human_review_projection.post_archive_runtime_change.pull_request, 910);
assert.equal(audit.current_human_review_projection.post_archive_runtime_change.commit, "13fce97431921d45874bf5dccd245751c3d1a9e4");
assert.equal(audit.current_human_review_projection.new_model_calls_required, false);
assert.equal(audit.current_human_review_projection.human_scores_autofilled, false);
assert.ok(audit.observed_defects.some((entry) => entry.id === "generic_path_copy" && entry.severity === "high"));
assert.ok(audit.observed_defects.some((entry) => entry.id === "low_information_display_anchor" && entry.severity === "high"));
assert.deepEqual(audit.evaluation_limitations.semantic_document_observed_arrays_empty, ["concepts", "claims", "relations", "tensions", "candidate_insights"]);
assert.equal(audit.evaluation_limitations.semantic_document_quality_status, "shadow_claims_relations_pending");
assert.equal(audit.release_boundary.independent_human_review_required, true);
assert.equal(audit.release_boundary.human_usefulness_gate, "open");
assert.equal(audit.release_boundary.automatic_persistence_allowed, false);
assert.equal(audit.release_boundary.projection_store_write_open, false);
assert.equal(audit.release_boundary.normal_chat_automatic_persistence_open, false);
assert.equal(audit.release_boundary.remote_write_open, false);

assert.equal(humanReview.status, "agent_pre_review_complete_independent_human_review_open");
assert.equal(humanReview.release_rule.independent_human_review_required, true);
assert.equal(humanReview.release_rule.minimum_acceptable_share, 0.8);
assert.equal(humanReview.release_rule.critical_provenance_errors_allowed, 0);
assert.equal(humanReview.release_rule.automatic_persistence_allowed, false);
assert.equal(humanReview.release_rule.reviewer_attestation_required, true);
assert.equal(humanReview.rubric.acceptable_score_minimum, 4);
assert.equal(humanReview.archived_live_review_input.available, true);
assert.equal(humanReview.archived_live_review_input.new_model_calls_required, false);
assert.equal(humanReview.archived_live_review_input.reviewer_scores_autofilled, false);
assert.equal(humanReview.archived_live_review_input.review_projection_mode, "current_read_only_projection_from_archived_live_insights");
assert.equal(humanReview.archived_live_review_input.current_product_code_applied, true);
assert.equal(humanReview.archived_live_review_input.admissible_for_human_scoring, false);
assert.equal(humanReview.archived_live_review_input.blocking_reason, "current_reprojection_product_coverage_below_release_threshold");
assert.equal(humanReview.archived_live_review_input.current_reprojection_evidence.canonical_main_sha, "88e9e9193be8cef717a626db2ecbb697a6ec192e");
assert.equal(humanReview.archived_live_review_input.current_reprojection_evidence.diagnostic_pull_request, 965);
assert.equal(humanReview.archived_live_review_input.current_reprojection_evidence.diagnostic_workflow_run, 35375565646);
assert.deepEqual(humanReview.archived_live_review_input.current_reprojection_evidence.product_coverage, {
  lists: { qualified_case_count: 16, qualified_case_share: 0.727273, passed: false },
  paths: { qualified_case_count: 18, qualified_case_share: 0.818182, passed: true },
  mindmap: { qualified_case_count: 17, qualified_case_share: 0.772727, passed: false }
});
assert.equal(humanReview.archived_live_review_input.current_reprojection_evidence.suppressed_case_count, 3);
assert.equal(humanReview.archived_live_review_input.current_reprojection_evidence.expected_suppressed_case_count, 3);
assert.equal(humanReview.archived_live_review_input.current_reprojection_evidence.release_gate_passed, false);
assert.equal(humanReview.review_workflow.explicit_draft_export, true);
assert.equal(humanReview.review_workflow.explicit_draft_import, true);
assert.equal(humanReview.review_workflow.automatic_browser_persistence, false);
assert.equal(humanReview.review_workflow.imported_scores_and_notes_restored, true);
assert.equal(humanReview.review_workflow.imported_human_attestation_restored, false);
assert.equal(humanReview.review_workflow.final_attestation_must_be_reconfirmed, true);
assert.equal(humanReview.review_workflow.canonical_rubric_rendered_in_review_surface, true);
assert.equal(humanReview.review_workflow.score_only_materialized_product_outputs, true);
assert.equal(humanReview.review_workflow.missing_or_selectively_filtered_products_require_human_scores, false);
assert.equal(humanReview.review_workflow.unexpectedly_materialized_expected_hidden_products_require_human_scores, true);
assert.equal(humanReview.release_rule.human_score_denominator, "materialized_product_outputs_only");
assert.equal(humanReview.review_workflow.current_reprojection_coverage_gate.coverage_case_count, 22);
assert.deepEqual(humanReview.review_workflow.current_reprojection_coverage_gate.excluded_calibration_cases, ["data_bus", "conflict_tourism"]);
assert.equal(humanReview.review_workflow.current_reprojection_coverage_gate.minimum_qualified_product_share, 0.8);
assert.deepEqual(humanReview.review_workflow.current_reprojection_coverage_gate.required_product_types, ["lists", "paths", "mindmap"]);
assert.equal(humanReview.review_workflow.current_reprojection_coverage_gate.coverage_must_pass_per_product_type, true);
assert.equal(humanReview.review_workflow.current_reprojection_coverage_gate.expected_suppressed_case_count, 3);
assert.equal(humanReview.review_workflow.current_reprojection_coverage_gate.required_suppression_share, 1);
assert.equal(humanReview.review_workflow.current_reprojection_coverage_gate.evaluated_after_current_code_reprojection, true);
assert.equal(humanReview.review_workflow.current_reprojection_coverage_gate.must_pass_before_human_scoring, true);
assert.equal(humanReview.review_workflow.human_scoring_input_ready, false);
assert.equal(humanReview.review_workflow.next_required_evidence, "fresh_explicit_release_browser_proof_on_current_main");
assert.equal(humanReview.archived_live_review_input.superseded_by_post_archive_runtime_changes, true);
assert.equal(humanReview.archived_live_review_input.post_archive_runtime_changes.source_grounded_product_usefulness.pull_request, 910);
assert.equal(humanReview.archived_live_review_input.post_archive_runtime_changes.source_grounded_product_usefulness.commit, "13fce97431921d45874bf5dccd245751c3d1a9e4");
assert.equal(humanReview.archived_live_review_input.post_archive_runtime_changes.source_grounded_product_usefulness.archived_runtime_had_source_bound_concept_adapter, false);
assert.equal(humanReview.archived_live_review_input.post_archive_runtime_changes.source_grounded_product_usefulness.current_runtime_has_source_bound_concept_adapter, true);
assert.equal(humanReview.review_workflow.fresh_paid_release_proof_requires_explicit_dispatch, true);
assert.equal(humanReview.review_workflow.automatic_pr_and_push_model_calls_allowed, false);
assert.equal(humanReview.review_workflow.rubric_source, "ops/evaluation/aha-projection-product-human-review-v2.json");
assert.ok(humanReview.case_reviews.every((entry) => entry.review_status === "open"));

assert.equal(liveArchive.schema, "aha_projection_product_live_review_archive_v2");
assert.equal(liveArchive.workflow_run_id, 32633381518);
assert.equal(liveArchive.artifact_id, 9491725428);
assert.equal(liveArchive.corpus_cases, 27);
assert.equal(liveArchive.successful_chat_count, 29);
assert.equal(liveArchive.critical_transport_failures, 0);
assert.equal(liveArchive.critical_provenance_errors_in_archived_results, 0);
assert.equal(liveArchive.import_mode, "local_json_then_current_read_only_reprojection");
assert.equal(liveArchive.review_projection_mode, "current_read_only_projection_from_archived_live_insights");
assert.equal(liveArchive.current_product_code_applied, true);
assert.equal(liveArchive.new_model_calls_required, false);
assert.equal(liveArchive.independent_human_review_complete, false);
assert.equal(liveArchive.human_review_must_not_be_autofilled, true);
assert.equal(liveArchive.pull_request, 894);
assert.equal(liveArchive.semantic_shapes_applied, true);
assert.equal(liveArchive.product_shapes.lists, "thematic_membership_v2");
assert.equal(liveArchive.product_shapes.paths, "ordered_inquiry_v2");
assert.equal(liveArchive.product_shapes.mindmap, "ranked_hierarchy_v2");

assert.match(browserSpec, /aha_projection_product_live_backend_preflight_v3/);
assert.match(browserSpec, /preflightResponse\.ok\(\)/);
assert.match(browserSpec, /AHA_LIVE_PRODUCT_MODE \|\| "offline"/);
assert.match(browserSpec, /aha_insight_synthesis_cost_control_v1/);
assert.match(browserSpec, /successfulChatResponses\.length/);
assert.match(browserSpec, /backend_http_failures/);
assert.match(browserSpec, /initialUsefulCaseCoverage/);
assert.match(browserSpec, /runCases/);

console.log("aha-projection-product-agent-quality-review-v2.test.cjs: OK (agent remediation recorded; independent human gate remains open)");
